select NREDS, COD_DIAO, BAIRRO, BAIRRO_NAO_CAD, LOG_TIPO, LOGRADOURO, LOGRADOURO_NAO_CAD, COMPLEMENTO_END, PONTO_REF, UN_AREA_MIL,
case    
    when MUNICIPIO != 'DIVINOPOLIS' then MUNICIPIO
    
    -- when NREDS in (select N_REDS from tbl_transferencia) then (SELECT destino from tbl_transferencia where NREDS = N_REDS)
    
    
    when (			           
				((BAIRRO IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '139ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
			or ((BAIRRO_NAO_CAD IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '139ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
			or ((LOGRADOURO IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '139ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
			or ((LOGRADOURO_NAO_CAD IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '139ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
			or ((NREDS IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '139ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
			or ((LOGRADOURO_CRUZ IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '139ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
			or ((LOGRADOURO_CRUZ_NAO_CAD IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '139ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
			or ((COMPLEMENTO_END IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '139ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
			or ((PONTO_REF IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '139ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )        
    )
    then '139 CIA'
        
   when (
			   
				((BAIRRO IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '53ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
			or ((BAIRRO_NAO_CAD IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '53ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
			or ((LOGRADOURO IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '53ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
			or ((LOGRADOURO_NAO_CAD IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '53ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
			or ((NREDS IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '53ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
			or ((LOGRADOURO_CRUZ IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '53ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
			or ((LOGRADOURO_CRUZ_NAO_CAD IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '53ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
			or ((COMPLEMENTO_END IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '139ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
			or ((PONTO_REF IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '139ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )				
    )
    then '53 CIA'
    
    when (
				((BAIRRO IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '142ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
			or ((BAIRRO_NAO_CAD IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '142ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
			or ((LOGRADOURO IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '142ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
			or ((LOGRADOURO_NAO_CAD IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '142ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
			or ((NREDS IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '142ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
			or ((LOGRADOURO_CRUZ IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '142ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
			or ((LOGRADOURO_CRUZ_NAO_CAD IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '142ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
			or ((COMPLEMENTO_END IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '139ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
			or ((PONTO_REF IN (SELECT VALIDADOR FROM tbl_validador_cia WHERE CIA_BASE = '139ª CIA PM'))AND(MUNICIPIO = 'DIVINOPOLIS') )
		)
    then '142 CIA'
    
        
    else 'other'
end
as Cia_Base
from tbl_crimes
where
NREDS not in (select NREDS from tbl_d_auditoria)

and MUNICIPIO = 'DIVINOPOLIS' limit 100000
;