SELECT
	YEAR(DTA_INICIO),
    NATCODIGO,
    COUNT(*)
FROM
	gdo.tbl_bos
WHERE
	MUNICIPIO IN ('DIVINOPOLIS', 'ITAUNA', 'ITATIAIUCU', 'CARMO DO CAJURU', 'CLAUDIO', 'SAO GONCALO DO PARA')
AND
	NATCODIGO LIKE 'A19%'
GROUP BY 
	YEAR(DTA_INICIO), NATCODIGO
with rollup;

