DROP TABLE tbl_recursos_humanos;

CREATE TABLE IF NOT EXISTS tbl_recursos_humanos

(

ORG_SERVIDOR varCHAR (50) NULL ,
MATRICULA VARCHAR (12) NOT NULL,
CARGO varchar (50),
NOME varchar (110),
CPF VARCHAR (14),
UNIDADE_SERVICO VARCHAR (100) NOT NULL,
MUNICIPIO VARCHAR (100) NULL,
PRIMARY KEY (MATRICULA)
)
DEFAULT CHARSET = utf8
ENGINE=InnoDB;



