CREATE TABLE IF NOT EXISTS tbl_veiculos

(
ID_VEIC int primary KEY auto_increment,
NREDS varCHAR (18) NOT NULL,
ORG_UN_REG VARCHAR (30) NULL,
UN_AREA_MIL VARCHAR (50) NULL,
UN_REGISTRO VARCHAR (100) NULL,
COD_DIAO VARCHAR (6),
T_C VARCHAR (9) NULL,
DATA_FATO DATE NULL,
HORA_FATO TIME NULL,
MUNICIPIO VARCHAR (50) NULL,
SITUACAO_VEICULO VARCHAR (20) NULL,
TIPO_VEICULO VARCHAR (100) NULL,
ANO_MODELO VARCHAR (20) NULL,
MARCA_MODELO VARCHAR (40) NULL,
QTDE_VEIC int(2)


)
DEFAULT CHARSET = utf8
ENGINE=InnoDB;


