CREATE TABLE IF NOT EXISTS tbl_policiais

(

ORG_SERVIDOR varCHAR (20) NULL ,
CARGO varchar (20),
NOME varchar (110),
MUNICIPIO VARCHAR (100) NULL,
CPF CHAR (11),
MATRICULA VARCHAR (7) NOT NULL PRIMARY KEY, 
-- LOTACAO varCHAR (20) NULL


)

ENGINE=InnoDB;

