CREATE TABLE IF NOT EXISTS tbl_localidades

(
ID int(11) NOT NULL AUTO_INCREMENT primary key,
CIA VARCHAR (11) NULL,
LATITUDE VARCHAR (15) NULL,
LONGITUDE VARCHAR (15) NULL,
LOCALIDADE VARCHAR (70) NULL,
TIPO VARCHAR (8) NULL,

SETOR VARCHAR (50) NULL,
SUBSETOR VARCHAR (50) NULL,
POPULACAO int null

)

ENGINE=InnoDB;