drop table if exists tbl_chamadas;

CREATE TABLE IF NOT EXISTS tbl_chamadas

(

NCHAMADA VARCHAR (15) NOT NULL PRIMARY KEY,
DATA_HR_CRIACAO datetime NULL,
DATA_CRIACAO date NULL,
HORA_CRIACAO TIME NULL,
LOCAL_FATO VARCHAR (200) NULL,
BAIRRO VARCHAR (200) NULL,
MUNICIPIO VARCHAR (50) NULL,
LATITUDE VARCHAR (15) NULL,
LONGITUDE VARCHAR (15) NULL,
COD_DIAO VARCHAR (12) NULL,
NATUREZA VARCHAR (100) NULL,
UN_RESPONSAVEL VARCHAR (100) NULL,
RECURSOS_EMPENHADOS VARCHAR (50) NULL,
ALERTA VARCHAR (30) NULL,
DESTAQUE VARCHAR (30) NULL,
ENVOLVE_AUTORIDADE VARCHAR (30) NULL,
CLASSIFICACAO VARCHAR (100) NULL,
SITUACAO VARCHAR (30) NULL,
DTA_HR_SIT_ATUAL datetime NULL,


UEOP varchar (15) NULL/*,
COMPANHIA VARCHAR (30) NULL,
FRACAO VARCHAR (50) NULL,
SETOR varchar (50) NULL,
VALIDADOR varchar (30) NULL*/



)
DEFAULT CHARSET = utf8
ENGINE=InnoDB;