-- INSERT INTO TABELA_ALVO(NOME, IDADE, DEPARTAMENTO)
-- SELECT CLI.NOME, CLI.IDADE, DEP.NOME_DEPT
-- FROM CLIENTE CLI, DEPARTAMENTO DEP
-- WHERE CLI.NUM_DEPT = DEP.NUM_DEPT;
-- 
-- 
-- 
-- INSERT INTO tbl_rat_resultado values
-- 
-- (RATNUM_ATIVIDADE, NATCODIGO, NATDESCRICAO, DTA_HRA_INCLUSAO, DTA_INICIO, HRA_INICIO, DTA_TERMINO, HRA_TERMINO, DES_ALVO_EVENTO, DES_LUGAR, NOM_OPERACAO, COD_UNIDADE_SERVICO, NOM_UNID_RESPONSAVEL,
-- TIPO_LOGRADOURO, LOGRADOURO, DES_ENDERECO, NUM_ENDERECO, COMPLEMENTO_ALFA, COMPLEMENTO_ENDERECO, NUM_COMPLEMENTAR, COD_BAIRRO, NOME_BAIRRO, TIPO_LOGRADOURO2, LOGRADOURO2, DES_ENDERECO2,
-- COD_MUNICIPIO, MUNICIPIO, LATITUDE, LONGITUDE, COD_UNIDADE_AREA, NOM_UNIDADE_AREA, DIGITADOR,
-- 
-- TEMPO_EXEC,
-- EFETIVO,
-- ABORDADOS,
-- VEIC_FISC,
-- LOCAIS_FISC,
-- PESSOAS_PRES_APREEND,
-- ARMAS_FOGO_APREEND,
-- MUNICOES_APREEND,
-- ARTEFATOS_EXPLOSIVOS_APREEND,
-- COLETES_APREEND,
-- DROGAS_APREEND,
-- VEICULOS_APREEND_REC, VIATURAS,
-- CIA_SEDE, COMPANHIA, SETOR),

INSERT INTO
	tbl_rat_resultados	
    (
		SELECT
			r.RATNUM_ATIVIDADE,
			r.NATCODIGO,
			r.NATDESCRICAO,
			r.DTA_HRA_INCLUSAO, 
			r.DTA_INICIO,
			r.HRA_INICIO,
			r.DTA_TERMINO,
			r.HRA_TERMINO,
			r.DES_ALVO_EVENTO,
			r.DES_LUGAR,
			r.NOM_OPERACAO,
			r.COD_UNIDADE_SERVICO,
			r.NOM_UNID_RESPONSAVEL,
			r.TIPO_LOGRADOURO,
			r.LOGRADOURO,
			r.DES_ENDERECO,
			r.NUM_ENDERECO,
			r.COMPLEMENTO_ALFA,
			r.COMPLEMENTO_ENDERECO,
			r.NUM_COMPLEMENTAR,
			r.COD_BAIRRO,
			r.NOME_BAIRRO,
			r.TIPO_LOGRADOURO2,
			r.LOGRADOURO2,
			r.DES_ENDERECO2,
			r.COD_MUNICIPIO,
			r.MUNICIPIO,
			r.LATITUDE,
			r.LONGITUDE,
			r.COD_UNIDADE_AREA,
			r.NOM_UNIDADE_AREA,
			r.DIGITADOR,
			#################################################################################
			(timediff(concat(r.DTA_TERMINO, ' ', r.HRA_TERMINO), concat(r.DTA_INICIO, ' ', r.HRA_INICIO))) as TEMPO_EXEC,
			count(distinct(e.num_matricula)) as EFETIVO,
			SUM(distinct(
				CASE
					WHEN p.descricao ='Qde de pessoas abordadas'
					THEN p.QUANTIDADE
					ELSE 0
				END)
			) AS ABORDADOS,
			#################################################################################
			SUM(distinct(
				CASE
					WHEN p.descricao ='Qde de veiculos fiscalizados'
					THEN p.QUANTIDADE
					ELSE 0
				END) 
			) AS VEIC_FISC,
			#################################################################################    
			SUM(DISTINCT(
				CASE
					WHEN p.descricao ='Qde de locais fiscalizados'
					THEN p.QUANTIDADE
					ELSE 0
				END)
			) AS LOCAIS_FISCALIZADOS,
			#################################################################################    
			SUM(distinct(
				CASE
					WHEN p.descricao IN ('FLAGRANTE DE ATO INFRACIONAL (AUTOR)',
										'FLAGRANTE DE ATO INFRACIONAL (CO-AUTOR)',
										'FLAGRANTE DE ATO INFRACIONAL (CONDUTOR DO VEICULO)',
										'FLAGRANTE DE CRIME / CONTRAVEN (AUTOR)',
										'FLAGRANTE DE CRIME / CONTRAVEN (CO-AUTOR)',
										'FLAGRANTE DE CRIME / CONTRAVEN (CONDUTOR DO VEICULO)',
										'MANDADO JUDICIAL (AUTOR)',
										'OUTRAS - PRISAO / APREENSAO (AUTOR)',
										'OUTRAS - PRISAO / APREENSAO (CO-AUTOR)',
										'OUTRAS - PRISAO / APREENSAO (CONDUTOR DO VEICULO)',
										'RECAPTURA (AUTOR)')
					THEN p.QUANTIDADE
					ELSE 0
				END)
			) AS PESSOAS_PRES_APREEND,
			#################################################################################    
			SUM(distinct(
				CASE
					WHEN p.descricao IN ('ARMAS DE FOGO DISSIMULADAS (USO RESTRITO) - APREENDIDO',
										'CARABINA / RIFLE - APREENDIDO',
										'ESPINGARDA / ESCOPETA - APREENDIDO',
										'ESPINGARDA POLVEIRA - APREENDIDO',
										'GARRUCHA - APREENDIDO',
										'GARRUCHA - RECOLHIDO',
										'METRALHADORA (USO RESTRITO) - APREENDIDO',
										'PISTOLA - APREENDIDO',
										'PISTOLETE (CALIBRE DE ESPINGARDA) - APREENDIDO',
										'REVOLVER - APREENDIDO',
										'SUBMETRALHADORA (USO RESTRITO) - APREENDIDO'
		)
					THEN p.QUANTIDADE
					ELSE 0
				END)
			) AS ARMAS_FOGO_APREEND,
			#################################################################################    
			SUM(distinct(
				CASE
					WHEN p.descricao IN ('CARTUCHO INTACTO (MUNICAO) DE ARMA DE FOGO DE (UNIDADE) - APREENDIDO',
										'CARTUCHO INTACTO (MUNICAO) DE ARMA DE FOGO DE (DUZIA) - APREENDIDO',
										'CARTUCHO INTACTO (MUNICAO) DE ARMA DE FOGO DE (CENTO) - APREENDIDO',
										'CARTUCHO INTACTO (MUNICAO) DE CALIBRE RESTRIT (UNIDADE) - APREENDIDO',
										'CARTUCHO INTACTO (MUNICAO) DE CALIBRE RESTRIT (DUZIA) - APREENDIDO',
										'CARTUCHO INTACTO (MUNICAO) DE CALIBRE RESTRIT (CENTO) - APREENDIDO',
										'CARTUCHO VAZIO DE MUNICAO DE USO RESTRITO (UNIDADE) - APREENDIDO',
										'CARTUCHO VAZIO DE MUNICAO DE USO RESTRITO (DUZIA) - APREENDIDO',
										'CARTUCHOS VAZIOS, SEMI-CARREGADOS (PERMITIDO) (UNIDADE) - APREENDIDO',
										'MUNICAO - DEMAIS SUBSTANCIAS, PRODUTOS SUJEIT (UNIDADE) - APREENDIDO'

		)
					THEN p.QUANTIDADE
					ELSE 0
				END)
			) AS MUNICOES_APREND,
			#################################################################################
			SUM(distinct(
				CASE
					WHEN p.descricao IN ('ARTEFATO EXPLOSIVO / BOMBA EXPLOSIVA / ETC (UNIDADE) - APREENDIDO',
										'MUNICAO QUIMICA, EXPLOSIVA OU FULMIGENA(RESTR (UNIDADE) - APREENDIDO',
										'OUTROS  - EXPLOSIVOS / MUNICOES / TIRO ESPORT (UNIDADE) - APREENDIDO'


						)
					THEN p.QUANTIDADE
					ELSE 0
				END)
			) AS ARTEFATOS_EXPLOSIVOS_APREEND,
			#################################################################################    
			SUM(distinct(
				CASE
					WHEN p.descricao IN ('COLETES CONTRA ARMAS DE FOGO DE USO PERMITIDO (UNIDADE) - APREENDIDO',
										'COLETES CONTRA ARMAS DE FOGO DE USO RESTRITO (UNIDADE) - APREENDIDO'
						)
					THEN p.QUANTIDADE
					ELSE 0
				END)
			) AS COLETES_APREEND,
			#################################################################################    
			SUM(distinct(
				CASE
					WHEN p.descricao IN ('BUCHA DE MACONHA (CENTO) - APREENDIDO',
										'BUCHA DE MACONHA (DUZIA) - APREENDIDO',
										'BUCHA DE MACONHA (GRAMA) - APREENDIDO',
										'BUCHA DE MACONHA (MILHEIRO) - APREENDIDO',
										'BUCHA DE MACONHA (UNIDADE) - APREENDIDO',
										'CIGARRO DE MACONHA (UNIDADE) - APREENDIDO',
										'COCAINA EM PO (CENTO) - APREENDIDO',
										'COCAINA EM PO (GRAMA) - APREENDIDO',
										'COCAINA EM PO (UNIDADE) - APREENDIDO',
										'CRACK EM PEDRAS (CENTO) - APREENDIDO',
										'CRACK EM PEDRAS (DUZIA) - APREENDIDO',
										'CRACK EM PEDRAS (GRAMA) - APREENDIDO',
										'CRACK EM PEDRAS (UNIDADE) - APREENDIDO',
										'CRACK EM QUILOGRAMAS (GRAMA) - APREENDIDO',
										'CRACK EM QUILOGRAMAS (QUILOGRAMA) - APREENDIDO',
										'CRACK EM QUILOGRAMAS (UNIDADE) - APREENDIDO',
										'ECSTASY / MDMA (UNIDADE) - APREENDIDO',
										'HAXIXE EM BOLA (DUZIA) - APREENDIDO',
										'HAXIXE EM BOLA (UNIDADE) - APREENDIDO',
										'HAXIXE EM TABLETE (QUILOGRAMA) (UNIDADE) - APREENDIDO',
										'LOLO (LITRO) - APREENDIDO',
										'LOLO (MILIGRAMA) - APREENDIDO',
										'LOLO (UNIDADE) - APREENDIDO',
										'MACONHA PRENSADA (BARRA / TABLETE) (CENTIMETRO) - APREENDIDO',
										'MACONHA PRENSADA (BARRA / TABLETE) (GRAMA) - APREENDIDO',
										'MACONHA PRENSADA (BARRA / TABLETE) (MILHEIRO) - APREENDIDO',
										'MACONHA PRENSADA (BARRA / TABLETE) (QUILOGRAMA) - APREENDIDO',
										'MACONHA PRENSADA (BARRA / TABLETE) (UNIDADE) - APREENDIDO',
										'OUTROS - COCAINA (CENTO) - APREENDIDO',
										'OUTROS - COCAINA (GRAMA) - APREENDIDO',
										'OUTROS - COCAINA (UNIDADE) - APREENDIDO',
										'OUTROS - CRACK (UNIDADE) - APREENDIDO',
										'OUTROS - HAXIXE (UNIDADE) - APREENDIDO',
										'OUTROS - LSD (UNIDADE) - APREENDIDO',
										'OUTROS - MACONHA (GRAMA) - APREENDIDO',
										'OUTROS - MACONHA (QUILOGRAMA) - APREENDIDO',
										'OUTROS - MACONHA (UNIDADE) - APREENDIDO',
										'PAPELOTES DE COCAINA (DUZIA) - APREENDIDO',
										'PAPELOTES DE COCAINA (GRAMA) - APREENDIDO',
										'PAPELOTES DE COCAINA (UNIDADE) - APREENDIDO',
										'PASTA DE COCAINA (GRAMA) - APREENDIDO',
										'PASTA DE COCAINA (UNIDADE) - APREENDIDO',
										'PLANTACAO (PE) DE MACONHA (UNIDADE) - APREENDIDO',
										'SEMENTE DE MACONHA (GRAMA) - APREENDIDO',
										'SEMENTE DE MACONHA (UNIDADE) - APREENDIDO'

						)
					THEN p.QUANTIDADE
					ELSE 0
				END)
			) AS DROGAS_APREEND,
			#################################################################################
			SUM(distinct(
				CASE
					WHEN p.descricao IN ('AUTOMOVEL - APREENDIDO',
										'AUTOMOVEL - RECUPERADO',
										'CAMINHAO - APREENDIDO',
										'CAMINHAO - RECUPERADO',
										'CAMINHAO/TRATOR - APREENDIDO',
										'CAMINHAO/TRATOR - RECUPERADO',
										'CAMINHONETE - APREENDIDO',
										'CAMINHONETE - RECUPERADO',
										'CAMIONETA - APREENDIDO',
										'CAMIONETA - RECUPERADO',
										'CICLOMOTOR - APREENDIDO',
										'CICLOMOTOR - RECUPERADO',
										'MICROONIBUS - APREENDIDO',
										'MICROONIBUS - RECUPERADO',
										'MOTOCICLETA - APREENDIDO',
										'MOTOCICLETA - RECUPERADO',
										'MOTONETA - APREENDIDO',
										'MOTONETA - RECUPERADO',
										'ONIBUS - APREENDIDO',
										'ONIBUS - RECUPERADO',
										'OUTROS - TIPOS DE VEICULO - APREENDIDO',
										'OUTROS - TIPOS DE VEICULO  - RECUPERADO',
										'REBOQUE - APREENDIDO',
										'REBOQUE - RECUPERADO',
										'TRATOR DE RODAS - RECUPERADO',
										'UTILITARIO (TIPO DE VEICULO) - APREENDIDO'

						)
					THEN p.QUANTIDADE
					ELSE 0
				END)
			) AS VEICULOS_APREEND_REC,
			#################################################################################
			count(distinct(v.NUM_PREFIXO)) as VIATURAS,
			#################################################################################
			fnc_cia_rat_bos (r.MUNICIPIO, r.RATNUM_ATIVIDADE, r.NOME_BAIRRO, r.LOGRADOURO, r.DES_ENDERECO, r.LOGRADOURO2, r.DES_ENDERECO2, r.COMPLEMENTO_ENDERECO, r.COMPLEMENTO_ALFA, r.LATITUDE)
				as CIA_SEDE,
			fnc_companhia_rat_bos (r.MUNICIPIO, r.RATNUM_ATIVIDADE, r.NOME_BAIRRO, r.LOGRADOURO, r.DES_ENDERECO, r.LOGRADOURO2, r.DES_ENDERECO2, r.COMPLEMENTO_ENDERECO, r.COMPLEMENTO_ALFA, r.LATITUDE)
				as COMPANHIA,
			classificaRat_BosPorSetor(r.MUNICIPIO , r.RATNUM_ATIVIDADE, r.NOME_BAIRRO, r.LOGRADOURO, r.DES_ENDERECO, r.LOGRADOURO2, r.DES_ENDERECO2, r.COMPLEMENTO_ENDERECO, r.COMPLEMENTO_ALFA, r.LATITUDE)
				as SETOR,
			fnc_tipo_validador_rat_bos (r.MUNICIPIO, r.RATNUM_ATIVIDADE, r.NOME_BAIRRO, r.LOGRADOURO, r.DES_ENDERECO, r.LOGRADOURO2, r.DES_ENDERECO2, r.COMPLEMENTO_ENDERECO, r.COMPLEMENTO_ALFA, r.LATITUDE)
				as VALIDADOR    
			
			
		FROM
			tbl_rat AS r
					
		LEFT OUTER JOIN
			tbl_rat_produtividade AS p
		ON p.RATNUM_ATIVIDADE = r.RATNUM_ATIVIDADE

		LEFT OUTER JOIN
			tbl_rat_efetivos AS e
		ON
			r.RATNUM_ATIVIDADE = e.NUM_ATIVIDADE
			
		LEFT OUTER JOIN
			tbl_rat_viaturas AS v
		ON
			v.NUM_ATIVIDADE = r.RATNUM_ATIVIDADE
						  
		WHERE r.municipio IN ('DIVINOPOLIS', 'CARMO DO CAJURU', 'CLAUDIO', 'SAO GONCALO DO PARA', 'ITAUNA', 'ITATIAIUCU')
		and r.DTA_INICIO between '2019-01-01' and '2019-01-01'
		GROUP BY RATNUM_ATIVIDADE
	);