DELIMITER $$
CREATE FUNCTION classificaRat_BosPorSetor(MUNICIPIO VARCHAR(50), RATNUM_ATIVIDADE VARCHAR (19), NOME_BAIRRO VARCHAR(50), LOGRADOURO VARCHAR(100), DES_ENDERECO VARCHAR(100),
LOGRADOURO2 VARCHAR(100), DES_ENDERECO2 VARCHAR(100), COMPLEMENTO_ENDERECO VARCHAR(30), COMPLEMENTO_ALFA VARCHAR(30), LATITUDE VARCHAR(20))
RETURNS VARCHAR(50)
BEGIN
	RETURN
		CASE
			WHEN
				MUNICIPIO = 'DIVINOPOLIS'
			THEN classificaRat_BosPorSetorDivinopolis(RATNUM_ATIVIDADE, NOME_BAIRRO, LOGRADOURO, DES_ENDERECO,
													LOGRADOURO2, DES_ENDERECO2, COMPLEMENTO_ENDERECO, COMPLEMENTO_ALFA, LATITUDE) -- AQUI CHAMA A FUNCAO QUE CLASSIFICA POR
			
			WHEN
				MUNICIPIO = 'ITAUNA'
			THEN classificaRat_BosPorSetorItauna(RATNUM_ATIVIDADE, NOME_BAIRRO, LOGRADOURO, DES_ENDERECO,
													LOGRADOURO2, DES_ENDERECO2, COMPLEMENTO_ENDERECO, COMPLEMENTO_ALFA, LATITUDE)
                                                            
			WHEN
				MUNICIPIO IN ('CARMO DO CAJURU', 'SAO GONCALO DO PARA')
			THEN 'C.CAJURU/S.G.PARÁ'
            
            WHEN
				MUNICIPIO = 'ITATIAIUCU'
			THEN 'LOURDES ITATIAIUCU'
            
            WHEN
				MUNICIPIO = 'CLAUDIO'
			THEN 'CLAUDIO'
            
            ELSE CONCAT(MUNICIPIO, ' / SETOR NÃO IDENTIFICADO')
	END;
END$$
DELIMITER ;

