DELIMITER $$
CREATE FUNCTION classificaRedsPorSetor(MUNICIPIO VARCHAR(100), NREDS VARCHAR (18), BAIRRO VARCHAR(50), BAIRRO_NAO_CAD VARCHAR(50), LOGRADOURO VARCHAR(100), LOGRADOURO_NAO_CAD VARCHAR(100),
LOGRADOURO_CRUZ VARCHAR(100), LOGRADOURO_CRUZ_NAO_CAD VARCHAR(100), COMPLEMENTO_END VARCHAR(50), PONTO_REF VARCHAR(50))
RETURNS VARCHAR(50)
BEGIN
	RETURN
		CASE
			WHEN
				MUNICIPIO = 'DIVINOPOLIS'
			THEN classificaRedsPorSetorDivinopolis(NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD,
															LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF)
			
			WHEN
				MUNICIPIO = 'ITAUNA'
			THEN classificaRedsPorSetorItauna(NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD,
															LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF)
                                                            
			WHEN
				MUNICIPIO IN ('CARMO DO CAJURU', 'SAO GONCALO DO PARA')
			THEN 'C.CAJURU/S.G.PARÁ'
            
            WHEN
				MUNICIPIO = 'ITATIAIUCU'
			THEN 'LOURDES ITATIAIUCU'
            
            WHEN
				MUNICIPIO = 'CLAUDIO'
			THEN 'CLAUDIO'
            
            ELSE CONCAT(MUNICIPIO, ' / SETOR NÃO IDENTIFICADO')
	END;
END$$
DELIMITER ;

SELECT
	*,
	classificaRedsPorSetor(MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) AS SETOR,
    fnc_companhia_reds(MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) AS CIA
FROM
	gdo.tbl_crimes;