DELIMITER $$
CREATE FUNCTION classificaRat_BosPorSetorItauna (RATNUM_ATIVIDADE VARCHAR (19), NOME_BAIRRO VARCHAR(50), LOGRADOURO VARCHAR(100), DES_ENDERECO VARCHAR(100),
LOGRADOURO2 VARCHAR(100), DES_ENDERECO2 VARCHAR(100), COMPLEMENTO_ENDERECO VARCHAR(30), COMPLEMENTO_ALFA VARCHAR(30), LATITUDE VARCHAR(20))
RETURNS VARCHAR (50)
BEGIN
	RETURN
		case -- case 2
	when
		RATNUM_ATIVIDADE in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CENTRO PADRE EUSTAQUIO' and VALIDADOR_TIPO = 'N_RAT') then 'CENTRO PADRE EUSTAQUIO'
	when
        RATNUM_ATIVIDADE in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTANENSE MORADA NOVA' and VALIDADOR_TIPO = 'N_RAT') then 'SANTANENSE MORADA NOVA'
	when
        RATNUM_ATIVIDADE in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'LOURDES ITATIAIUCU' and VALIDADOR_TIPO = 'N_RAT') then 'LOURDES ITATIAIUCU'

	else -- case2
		case -- case 3
        when
			NOME_BAIRRO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CENTRO PADRE EUSTAQUIO'and VALIDADOR_TIPO = 'BAIRRO')  then 'CENTRO PADRE EUSTAQUIO'
		when
            NOME_BAIRRO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTANENSE MORADA NOVA' and VALIDADOR_TIPO = 'BAIRRO')  then 'SANTANENSE MORADA NOVA'
		when
            NOME_BAIRRO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'LOURDES ITATIAIUCU' and VALIDADOR_TIPO = 'BAIRRO') then 'LOURDES ITATIAIUCU'
		else -- case 3
        
			case -- case 4
			when
				LOGRADOURO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CENTRO PADRE EUSTAQUIO' and VALIDADOR_TIPO = 'LOGRADOURO') then 'CENTRO PADRE EUSTAQUIO'
			when
                LOGRADOURO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTANENSE MORADA NOVA' and VALIDADOR_TIPO = 'LOGRADOURO') then 'SANTANENSE MORADA NOVA'
			when
                LOGRADOURO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'LOURDES ITATIAIUCU' and VALIDADOR_TIPO = 'LOGRADOURO') then 'LOURDES ITATIAIUCU'

			else -- case 4
            --         
            	case -- case 5
				when
					DES_ENDERECO  in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CENTRO PADRE EUSTAQUIO' and VALIDADOR_TIPO = 'LOGRADOURO') then 'CENTRO PADRE EUSTAQUIO'
				when
					DES_ENDERECO  in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTANENSE MORADA NOVA' and VALIDADOR_TIPO = 'LOGRADOURO') then 'SANTANENSE MORADA NOVA'
				when	
                    DES_ENDERECO  in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'LOURDES ITATIAIUCU' and VALIDADOR_TIPO = 'LOGRADOURO') then 'LOURDES ITATIAIUCU'

				else -- case 5
					case -- case 6
					when
						LOGRADOURO2 in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CENTRO PADRE EUSTAQUIO' and VALIDADOR_TIPO = 'LOGRADOURO_NAO_CAD') then 'CENTRO PADRE EUSTAQUIO'
					when	
                        LOGRADOURO2 in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTANENSE MORADA NOVA' and VALIDADOR_TIPO = 'LOGRADOURO_NAO_CAD') then 'SANTANENSE MORADA NOVA'
					when	
                        LOGRADOURO2 in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'LOURDES ITATIAIUCU' and VALIDADOR_TIPO = 'LOGRADOURO_NAO_CAD') then 'LOURDES ITATIAIUCU'
		
					else -- case 6
						case -- case 7
						when
							DES_ENDERECO2 in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CENTRO PADRE EUSTAQUIO' and VALIDADOR_TIPO = 'LOGRADOURO_NAO_CAD') then 'CENTRO PADRE EUSTAQUIO'
						when	
                            DES_ENDERECO2 in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTANENSE MORADA NOVA' and VALIDADOR_TIPO = 'LOGRADOURO_NAO_CAD') then 'SANTANENSE MORADA NOVA'
						when	
                            DES_ENDERECO2 in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'LOURDES ITATIAIUCU' and VALIDADOR_TIPO = 'LOGRADOURO_NAO_CAD') then 'LOURDES ITATIAIUCU'
	
						else -- case 7
						
							case -- case 8
							when
								COMPLEMENTO_ENDERECO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CENTRO PADRE EUSTAQUIO' and VALIDADOR_TIPO = 'COMPLEMENTO_END') then 'CENTRO PADRE EUSTAQUIO'
							when	
                                COMPLEMENTO_ENDERECO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTANENSE MORADA NOVA' and VALIDADOR_TIPO = 'COMPLEMENTO_END') then 'SANTANENSE MORADA NOVA'
							when	
                                COMPLEMENTO_ENDERECO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'LOURDES ITATIAIUCU' and VALIDADOR_TIPO = 'COMPLEMENTO_END') then 'LOURDES ITATIAIUCU'
							else -- case 8
								case -- case 9
								when
									COMPLEMENTO_ALFA in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CENTRO PADRE EUSTAQUIO' and VALIDADOR_TIPO = 'COMPLEMENTO_END') then 'CENTRO PADRE EUSTAQUIO'
								when
                                    COMPLEMENTO_ALFA in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTANENSE MORADA NOVA' and VALIDADOR_TIPO = 'COMPLEMENTO_END') then 'SANTANENSE MORADA NOVA'
								when	
                                    COMPLEMENTO_ALFA in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'LOURDES ITATIAIUCU' and VALIDADOR_TIPO = 'COMPLEMENTO_END') then 'LOURDES ITATIAIUCU'

							                   
								else -- case 9
									case -- case 10
									when
										LATITUDE in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CENTRO PADRE EUSTAQUIO' and VALIDADOR_TIPO = 'PONTO_REF') then 'CENTRO PADRE EUSTAQUIO'
									when	
                                        LATITUDE in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTANENSE MORADA NOVA' and VALIDADOR_TIPO = 'PONTO_REF') then 'SANTANENSE MORADA NOVA'
									when	
                                        LATITUDE in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'LOURDES ITATIAIUCU' and VALIDADOR_TIPO = 'PONTO_REF') then 'LOURDES ITATIAIUCU'


									else 'other'-- case 10
									end -- case 9
                                end -- case 9
                            end -- case 8
                        end -- case 7
                    end -- case 6
                end -- case 5
			end -- case 4
        end -- case 3
	end -- case 2
 ;
END$$
DELIMITER ;
