CREATE TABLE IF NOT EXISTS tbl_escolas

(

ID_ESC int primary KEY auto_increment,
COD_SRE varCHAR (18) NOT null,
COD_MUNICIPIO VARCHAR (30) NULL,
MUNICIPIO VARCHAR (50) NULL,
COD_ESCOLA VARCHAR (9) NULL,
NOME_ESTABELECIMENTO_ENSINO VARCHAR (150) NULL,
LATITUDE VARCHAR (15) NULL,
LONGITUDE VARCHAR (15) NULL,
DEPENDENCIA_ADMINISTRATIVA VARCHAR (50) NULL,
LOCALIZACAO VARCHAR (100) NULL,
ENDERECO VARCHAR (100) NULL,
N_LOG VARCHAR (20) NULL,
COMPLEMENTO VARCHAR (30) NULL,
BAIRRO VARCHAR (50) NULL,
CEP VARCHAR (50) NULL,
DDD VARCHAR (3) NULL,
TELEFONE VARCHAR (50) NULL,
TELEFONE_PUBLICO VARCHAR (50) NULL,
EMAIL VARCHAR (50) NULL


-- PRIMARY KEY (NREDS, TIPO_ARMA)

)
DEFAULT CHARSET = utf8
ENGINE=InnoDB;

    