SELECT
COALESCE(COMPANHIA, 'TOTAL GERAL')  AS COMPANHIA,
CASE
 WHEN ((COMPANHIA IS NOT NULL) AND (Cia_Base IS NULL))
  THEN CONCAT('Subtotal - ', COMPANHIA)
  WHEN (COMPANHIA IS NOT NULL AND CIA_BASE IS NOT NULL)
  THEN CIA_BASE
  WHEN (COMPANHIA IS NULL AND CIA_BASE IS NULL)
  THEN '.........................'
END AS CIA_BASE,
VISITAS FROM
(
 SELECT
 COMPANHIA, 
 CIA_BASE, 
 SUM(VT) AS VISITAS
 FROM vw_valid_bos
 GROUP BY COMPANHIA, Cia_Base WITH ROLLUP
) TOTAL
ORDER BY
CASE
 WHEN(COMPANHIA IS NOT NULL) THEN 0
 ELSE 1
END,
COMPANHIA DESC,
CASE
 WHEN(CIA_BASE IS NOT NULL) THEN 0
 ELSE 1
END,
Cia_Base DESC;