SELECT * FROM seo.tbl_envolvidos

where data_fato between '2018-01-01' and '2018-12-31'

AND MUNICIPIO IN ('DIVINOPOLIS', 'CARMO DO CAJURU', 'CLAUDIO', 'SAO GONCALO DO PARA', 'ITAUNA', 'ITATIAIUCU')


AND (( -- INÍCIO CONDIÇÃO PRINCIPAL		
				(COD_DIAO in ('B01121') and T_C = 'CONSUMADO')	  
				or  COD_DELITO in ('B01121') and T_C_DELITO = 'CONSUMADO')
			) -- FIM CONDIÇÃO PARA  (NATUREZAS)

AND GRAU_LESAO = 'FATAL'

AND GRUPO_TIPO_ENVOL = 'VITIMA'
;