drop  FUNCTION IF EXISTS fnc_setor_reds_7rpm;  


DELIMITER $$
CREATE FUNCTION fnc_setor_reds_7rpm (MUNICIPIO VARCHAR(100), NREDS VARCHAR (18), BAIRRO VARCHAR(50), BAIRRO_NAO_CAD VARCHAR(50), LOGRADOURO VARCHAR(100), LOGRADOURO_NAO_CAD VARCHAR(100),
LOGRADOURO_CRUZ VARCHAR(100), LOGRADOURO_CRUZ_NAO_CAD VARCHAR(100), COMPLEMENTO_END VARCHAR(50), PONTO_REF VARCHAR(50))
RETURNS VARCHAR(50) deterministic
BEGIN
	RETURN
		CASE
			WHEN
				MUNICIPIO = 'DIVINOPOLIS'
			THEN fnc_setor_reds_div (NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD,
															LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF)
		ELSE
			
			CASE
				WHEN
					MUNICIPIO = 'ITAUNA'
				THEN fnc_setor_reds_ita (NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD,
																LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF)
			ELSE
            
				CASE
					WHEN
					MUNICIPIO = 'NOVA SERRANA'
					THEN fnc_setor_reds_nse (NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD,
																LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF)
			ELSE                                              
			
					CASE
						WHEN
							MUNICIPIO IN ('CARMO DO CAJURU', 'SAO GONCALO DO PARA')
						THEN 'C.CAJURU/S.G.PARÁ'
            
					ELSE
						CASE
							WHEN
								MUNICIPIO = 'ITATIAIUCU'
							THEN 'LOURDES ITATIAIUCU'
						ELSE	
								
                            CASE    
                                WHEN
									MUNICIPIO = 'CLAUDIO'
								THEN 'CLAUDIO'
            
									ELSE MUNICIPIO -- CONCAT(MUNICIPIO, ' SETOR')
							
						END
					END
				END
			END
        END
    END;
END$$
DELIMITER ;

