drop  FUNCTION IF EXISTS fnc_setor_reds_ita;

DELIMITER $$
CREATE FUNCTION fnc_setor_reds_ita (NREDS VARCHAR (18), BAIRRO VARCHAR(50), BAIRRO_NAO_CAD VARCHAR(50), LOGRADOURO VARCHAR(100), LOGRADOURO_NAO_CAD VARCHAR(100),
LOGRADOURO_CRUZ VARCHAR(100), LOGRADOURO_CRUZ_NAO_CAD VARCHAR(100), COMPLEMENTO_END VARCHAR(50), PONTO_REF VARCHAR(50))
RETURNS VARCHAR (50) deterministic
BEGIN
	RETURN
	case -- case 2
		when
			NREDS in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CENTRO PADRE EUSTAQUIO' and VALIDADOR_TIPO = 'N_REDS') then 'CENTRO PADRE EUSTAQUIO'
		when
			NREDS in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTANENSE MORADA NOVA' and VALIDADOR_TIPO = 'N_REDS') then 'SANTANENSE MORADA NOVA'
		when
			NREDS in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'LOURDES ITATIAIUCU' and VALIDADOR_TIPO = 'N_REDS') then 'LOURDES ITATIAIUCU'
		else -- case2
			case -- case 3
			when
				BAIRRO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CENTRO PADRE EUSTAQUIO'and VALIDADOR_TIPO = 'BAIRRO')  then 'CENTRO PADRE EUSTAQUIO'
			when
				BAIRRO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTANENSE MORADA NOVA' and VALIDADOR_TIPO = 'BAIRRO')  then 'SANTANENSE MORADA NOVA'
			when
				BAIRRO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'LOURDES ITATIAIUCU' and VALIDADOR_TIPO = 'BAIRRO') then 'LOURDES ITATIAIUCU'
			else -- case 3
				case -- case 4
				when
					BAIRRO_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CENTRO PADRE EUSTAQUIO' and VALIDADOR_TIPO = 'BAIRRO_NAO_CAD') then 'CENTRO PADRE EUSTAQUIO'
				when
					BAIRRO_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTANENSE MORADA NOVA' and VALIDADOR_TIPO = 'BAIRRO_NAO_CAD') then 'SANTANENSE MORADA NOVA'
				when
					BAIRRO_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'LOURDES ITATIAIUCU' and VALIDADOR_TIPO = 'BAIRRO_NAO_CAD') then 'LOURDES ITATIAIUCU'
				else -- case 4
				
					case -- case 5
					when
						LOGRADOURO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CENTRO PADRE EUSTAQUIO' and VALIDADOR_TIPO = 'LOGRADOURO') then 'CENTRO PADRE EUSTAQUIO'
					when
						LOGRADOURO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTANENSE MORADA NOVA' and VALIDADOR_TIPO = 'LOGRADOURO') then 'SANTANENSE MORADA NOVA'
					when	
						LOGRADOURO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'LOURDES ITATIAIUCU' and VALIDADOR_TIPO = 'LOGRADOURO') then 'LOURDES ITATIAIUCU'
					else -- case 5
						case -- case 6
						when
							LOGRADOURO_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CENTRO PADRE EUSTAQUIO' and VALIDADOR_TIPO = 'LOGRADOURO_NAO_CAD') then 'CENTRO PADRE EUSTAQUIO'
						when	
							LOGRADOURO_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTANENSE MORADA NOVA' and VALIDADOR_TIPO = 'LOGRADOURO_NAO_CAD') then 'SANTANENSE MORADA NOVA'
						when	
							LOGRADOURO_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'LOURDES ITATIAIUCU' and VALIDADOR_TIPO = 'LOGRADOURO_NAO_CAD') then 'LOURDES ITATIAIUCU'
						else -- case 6
							case -- case 7
							when
								LOGRADOURO_CRUZ in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CENTRO PADRE EUSTAQUIO' and VALIDADOR_TIPO = 'LOGRADOURO_CRUZ') then 'CENTRO PADRE EUSTAQUIO'
							when	
								LOGRADOURO_CRUZ in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTANENSE MORADA NOVA' and VALIDADOR_TIPO = 'LOGRADOURO_CRUZ') then 'SANTANENSE MORADA NOVA'
							when	
								LOGRADOURO_CRUZ in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'LOURDES ITATIAIUCU' and VALIDADOR_TIPO = 'LOGRADOURO_CRUZ') then 'LOURDES ITATIAIUCU'
						else -- case 7
						
							case -- case 8
								when
									LOGRADOURO_CRUZ_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CENTRO PADRE EUSTAQUIO' and VALIDADOR_TIPO = 'LOGRADOURO_CRUZ_NAO_CAD') then 'CENTRO PADRE EUSTAQUIO'
								when	
									LOGRADOURO_CRUZ_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTANENSE MORADA NOVA' and VALIDADOR_TIPO = 'LOGRADOURO_CRUZ_NAO_CAD') then 'SANTANENSE MORADA NOVA'
								when	
									LOGRADOURO_CRUZ_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'LOURDES ITATIAIUCU' and VALIDADOR_TIPO = 'LOGRADOURO_CRUZ_NAO_CAD') then 'LOURDES ITATIAIUCU'

								else -- case 8
									case -- case 9
									when
										COMPLEMENTO_END in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CENTRO PADRE EUSTAQUIO' and VALIDADOR_TIPO = 'COMPLEMENTO_END') then 'CENTRO PADRE EUSTAQUIO'
									when
										COMPLEMENTO_END in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTANENSE MORADA NOVA' and VALIDADOR_TIPO = 'COMPLEMENTO_END') then 'SANTANENSE MORADA NOVA'
									when	
										COMPLEMENTO_END in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'LOURDES ITATIAIUCU' and VALIDADOR_TIPO = 'COMPLEMENTO_END') then 'LOURDES ITATIAIUCU'

												   
									else -- case 9
										case -- case 10
										when
											PONTO_REF in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CENTRO PADRE EUSTAQUIO' and VALIDADOR_TIPO = 'PONTO_REF') then 'CENTRO PADRE EUSTAQUIO'
										when	
											PONTO_REF in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTANENSE MORADA NOVA' and VALIDADOR_TIPO = 'PONTO_REF') then 'SANTANENSE MORADA NOVA'
										when	
											PONTO_REF in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'LOURDES ITATIAIUCU' and VALIDADOR_TIPO = 'PONTO_REF') then 'LOURDES ITATIAIUCU'
										else 'other'-- case 10
										end -- case 9
									end -- case 9
								end -- case 8
							end -- case 7
						end -- case 6
					end -- case 5
				end -- case 4
			end -- case 3
		end; -- case 2
END$$
DELIMITER ;