drop  FUNCTION IF EXISTS fnc_setor_reds_nse;


DELIMITER $$
CREATE FUNCTION fnc_setor_reds_nse (NREDS VARCHAR (18), BAIRRO VARCHAR(50), BAIRRO_NAO_CAD VARCHAR(50), LOGRADOURO VARCHAR(100), LOGRADOURO_NAO_CAD VARCHAR(100),
LOGRADOURO_CRUZ VARCHAR(100), LOGRADOURO_CRUZ_NAO_CAD VARCHAR(100), COMPLEMENTO_END VARCHAR(50), PONTO_REF VARCHAR(50))
RETURNS VARCHAR (50) deterministic
BEGIN
	RETURN
		case -- case 2
			when
				NREDS in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CONCESSO ELIAS' and VALIDADOR_TIPO = 'N_REDS') then 'CONCESSO ELIAS'
			when
				NREDS in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SUPER CENTRO' and VALIDADOR_TIPO = 'N_REDS') then 'SUPER CENTRO'
			when
				NREDS in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTA SARA' and VALIDADOR_TIPO = 'N_REDS') then 'SANTA SARA'
			when
				NREDS in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'ROMEU DUARTE' and VALIDADOR_TIPO = 'N_REDS') then 'ROMEU DUARTE'
			when
				NREDS in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SAO GERALDO' and VALIDADOR_TIPO = 'N_REDS') then 'SAO GERALDO'
			when
				NREDS in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'ZONA RURAL' and VALIDADOR_TIPO = 'N_REDS') then 'ZONA RURAL'
			
		else -- case2
			case -- case 3
				when
					BAIRRO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CONCESSO ELIAS'and VALIDADOR_TIPO = 'BAIRRO')  then 'CONCESSO ELIAS'
				when
					BAIRRO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SUPER CENTRO' and VALIDADOR_TIPO = 'BAIRRO')  then 'SUPER CENTRO'
				when
					BAIRRO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTA SARA' and VALIDADOR_TIPO = 'BAIRRO' AND MUNICIPIO = 'NOVA SERRANA') then 'SANTA SARA'
				when
					BAIRRO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'ROMEU DUARTE' and VALIDADOR_TIPO = 'BAIRRO')  then 'ROMEU DUARTE'
				when
					BAIRRO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SAO GERALDO' and VALIDADOR_TIPO = 'BAIRRO')  then 'SAO GERALDO'
				when
					BAIRRO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'ZONA RURAL' and VALIDADOR_TIPO = 'BAIRRO') then 'ZONA RURAL'

			else -- case 3
				case -- case 4
					when
						BAIRRO_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CONCESSO ELIAS' and VALIDADOR_TIPO = 'BAIRRO_NAO_CAD') then 'CONCESSO ELIAS'
					when
						BAIRRO_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SUPER CENTRO' and VALIDADOR_TIPO = 'BAIRRO_NAO_CAD') then 'SUPER CENTRO'
					when
						BAIRRO_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTA SARA' and VALIDADOR_TIPO = 'BAIRRO_NAO_CAD') then 'SANTA SARA'
					when
						BAIRRO_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'ROMEU DUARTE' and VALIDADOR_TIPO = 'BAIRRO_NAO_CAD') then 'ROMEU DUARTE'
					when
						BAIRRO_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SAO GERALDO' and VALIDADOR_TIPO = 'BAIRRO_NAO_CAD') then 'SAO GERALDO'
					when
						BAIRRO_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'ZONA RURAL' and VALIDADOR_TIPO = 'BAIRRO_NAO_CAD') then 'ZONA RURAL'

				else -- case 4					
					case -- case 5
						when
							LOGRADOURO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CONCESSO ELIAS' and VALIDADOR_TIPO = 'LOGRADOURO') then 'CONCESSO ELIAS'
						when
							LOGRADOURO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SUPER CENTRO' and VALIDADOR_TIPO = 'LOGRADOURO') then 'SUPER CENTRO'
						when	
							LOGRADOURO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTA SARA' and VALIDADOR_TIPO = 'LOGRADOURO') then 'SANTA SARA'
						when
							LOGRADOURO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'ROMEU DUARTE' and VALIDADOR_TIPO = 'LOGRADOURO') then 'ROMEU DUARTE'
						when
							LOGRADOURO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SAO GERALDO' and VALIDADOR_TIPO = 'LOGRADOURO') then 'SAO GERALDO'
						when	
							LOGRADOURO in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'ZONA RURAL' and VALIDADOR_TIPO = 'LOGRADOURO') then 'ZONA RURAL'

					else -- case 5
						case -- case 6
							when
								LOGRADOURO_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CONCESSO ELIAS' and VALIDADOR_TIPO = 'LOGRADOURO_NAO_CAD') then 'CONCESSO ELIAS'
							when	
								LOGRADOURO_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SUPER CENTRO' and VALIDADOR_TIPO = 'LOGRADOURO_NAO_CAD') then 'SUPER CENTRO'
							when	
								LOGRADOURO_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTA SARA' and VALIDADOR_TIPO = 'LOGRADOURO_NAO_CAD') then 'SANTA SARA'
							when
								LOGRADOURO_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'ROMEU DUARTE' and VALIDADOR_TIPO = 'LOGRADOURO_NAO_CAD') then 'ROMEU DUARTE'
							when	
								LOGRADOURO_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SAO GERALDO' and VALIDADOR_TIPO = 'LOGRADOURO_NAO_CAD') then 'SAO GERALDO'
							when	
								LOGRADOURO_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'ZONA RURAL' and VALIDADOR_TIPO = 'LOGRADOURO_NAO_CAD') then 'ZONA RURAL'
			
						else -- case 6
							case -- case 7
								when
									LOGRADOURO_CRUZ in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CONCESSO ELIAS' and VALIDADOR_TIPO = 'LOGRADOURO_CRUZ') then 'CONCESSO ELIAS'
								when	
									LOGRADOURO_CRUZ in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SUPER CENTRO' and VALIDADOR_TIPO = 'LOGRADOURO_CRUZ') then 'SUPER CENTRO'
								when	
									LOGRADOURO_CRUZ in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTA SARA' and VALIDADOR_TIPO = 'LOGRADOURO_CRUZ') then 'SANTA SARA'
								when
									LOGRADOURO_CRUZ in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'ROMEU DUARTE' and VALIDADOR_TIPO = 'LOGRADOURO_CRUZ') then 'ROMEU DUARTE'
								when	
									LOGRADOURO_CRUZ in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SAO GERALDO' and VALIDADOR_TIPO = 'LOGRADOURO_CRUZ') then 'SAO GERALDO'
								when	
									LOGRADOURO_CRUZ in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'ZONA RURAL' and VALIDADOR_TIPO = 'LOGRADOURO_CRUZ') then 'ZONA RURAL'
		
							else -- case 7								
								case -- case 8
									when
										LOGRADOURO_CRUZ_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CONCESSO ELIAS' and VALIDADOR_TIPO = 'LOGRADOURO_CRUZ_NAO_CAD') then 'CONCESSO ELIAS'
									when	
										LOGRADOURO_CRUZ_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SUPER CENTRO' and VALIDADOR_TIPO = 'LOGRADOURO_CRUZ_NAO_CAD') then 'SUPER CENTRO'
									when	
										LOGRADOURO_CRUZ_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTA SARA' and VALIDADOR_TIPO = 'LOGRADOURO_CRUZ_NAO_CAD') then 'SANTA SARA'
									when
										LOGRADOURO_CRUZ_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'ROMEU DUARTE' and VALIDADOR_TIPO = 'LOGRADOURO_CRUZ_NAO_CAD') then 'ROMEU DUARTE'
									when	
										LOGRADOURO_CRUZ_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SAO GERALDO' and VALIDADOR_TIPO = 'LOGRADOURO_CRUZ_NAO_CAD') then 'SAO GERALDO'
									when	
										LOGRADOURO_CRUZ_NAO_CAD in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'ZONA RURAL' and VALIDADOR_TIPO = 'LOGRADOURO_CRUZ_NAO_CAD') then 'ZONA RURAL'
									
								else -- case 8
									case -- case 9
										when
											COMPLEMENTO_END in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CONCESSO ELIAS' and VALIDADOR_TIPO = 'COMPLEMENTO_END') then 'CONCESSO ELIAS'
										when
											COMPLEMENTO_END in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SUPER CENTRO' and VALIDADOR_TIPO = 'COMPLEMENTO_END') then 'SUPER CENTRO'
										when	
											COMPLEMENTO_END in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTA SARA' and VALIDADOR_TIPO = 'COMPLEMENTO_END') then 'SANTA SARA'
										when
											COMPLEMENTO_END in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'ROMEU DUARTE' and VALIDADOR_TIPO = 'COMPLEMENTO_END') then 'ROMEU DUARTE'
										when
											COMPLEMENTO_END in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SAO GERALDO' and VALIDADOR_TIPO = 'COMPLEMENTO_END') then 'SAO GERALDO'
										when	
											COMPLEMENTO_END in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'ZONA RURAL' and VALIDADOR_TIPO = 'COMPLEMENTO_END') then 'ZONA RURAL'
												   
									else -- case 9
										case -- case 10
											when
												PONTO_REF in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'CONCESSO ELIAS' and VALIDADOR_TIPO = 'PONTO_REF') then 'CONCESSO ELIAS'
											when	
												PONTO_REF in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SUPER CENTRO' and VALIDADOR_TIPO = 'PONTO_REF') then 'SUPER CENTRO'
											when	
												PONTO_REF in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SANTA SARA' and VALIDADOR_TIPO = 'PONTO_REF') then 'SANTA SARA'
											when
												PONTO_REF in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'ROMEU DUARTE' and VALIDADOR_TIPO = 'PONTO_REF') then 'ROMEU DUARTE'
											when	
												PONTO_REF in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'SAO GERALDO' and VALIDADOR_TIPO = 'PONTO_REF') then 'SAO GERALDO'
											when	
												PONTO_REF in (SELECT VALIDADOR FROM tbl_validadores WHERE SETOR = 'ZONA RURAL' and VALIDADOR_TIPO = 'PONTO_REF') then 'ZONA RURAL'

										else 'other'-- case 10
										end -- case 10
									end -- case 9
								end -- case 8
							end -- case 7
						end -- case 6
					end -- case 5
				end -- case 4
			end -- case 3
		end ;
END$$
DELIMITER ;