select *, count(*) as qtde from rat

where DTA_inicio BETWEEN '2017-01-01' AND '2018-12-31'
-- and RATNUM_ATIVIDADE '2018-017776630-001',
and MUNICIPIO in ('IGARATINGA',
'MARAVILHAS',
'ONCA DO PITANGUI',
'PAPAGAIOS',
'PARA DE MINAS',
'PEQUI',
'SAO JOSE DA VARGINHA',
'CARMO DO CAJURU',
'CLAUDIO',
'DIVINOPOLIS',
'ITATIAIUCU',
'ITAUNA',
'SAO GONCALO DO PARA',
'ARAUJOS',
'CONCEICAO DO PARA',
'LEANDRO FERREIRA',
'NOVA SERRANA',
'PERDIGAO',
'PITANGUI',
'ARCOS',
'BAMBUI',
'CAMACHO',
'CORREGO FUNDO',
'FORMIGA',
'IGUATAMA',
'ITAPECERICA',
'MEDEIROS',
'PAINS',
'PIMENTA',
'SAO SEBASTIAO DO OESTE',
'TAPIRAI',
'ABAETE',
'BIQUINHAS',
'BOM DESPACHO',
'CEDRO DO ABAETE',
'CORREGO DANTA',
'DORES DO INDAIA',
'ESTRELA DO INDAIA',
'JAPARAIBA',
'LAGOA DA PRATA',
'LUZ',
'MARTINHO CAMPOS',
'MOEMA',
'MORADA NOVA DE MINAS',
'PAINEIRAS',
'PEDRA DO INDAIA',
'POMPEU',
'QUARTEL GERAL',
'SANTO ANTONIO DO MONTE',
'SERRA DA SAUDADE')
group by RATNUM_ATIVIDADE

HAVING qtde > 1

ou

SELECT RATNUM_ATIVIDADE, Count(*) FROM rat
where MUNICIPIO = "divinopolis"
GROUP BY natdescricao
HAVING Count(*) > 1

ou

select dta_inicio, natdescricao, max(ratnum_atividade), count(*) as freq from rat
where MUNICIPIO = "divinopolis"
group by RATNUM_ATIVIDADE having freq >1 


LIMIT 0, 1000