SELECT SUBAREA, SETOR, ENDERECO,

(SELECT COUNT(*) FROM TBL_OCORRENCIAS
WHERE LATITUDE >= TBL_QUADRICULAS.MINY AND LATITUDE <= TBL_QUADRICULAS.MAXY
AND LONGITUDE >= TBL_QUADRICULAS.MINX AND LONGITUDE <= TBL_QUADRICULAS.MAXX
AND DATA_FATO  ='2018-01-31'
) AS CRIMES


FROM TBL_QUADRICULAS

WHERE SUBAREA = '139ª Cia PM'

GROUP BY ENDERECO
HAVING CRIMES >= 0
;

OBJECTID = SUMX(FILTER(d_quadriculas;fbase[Latitude]>=d_quadriculas[MINY]&&fbase[Latitude]<=d_quadriculas[MAXY]
    && fbase[Longitude]>=d_quadriculas[MINX]&&fbase[Longitude]<=d_quadriculas[MAXX]
    );d_quadriculas[OBJECTID])