-- envolvidos

SELECT MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF, 
				fnc_companhia_reds_7rpm (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) AS COMPANHIA,
				-- fnc_cia_sede_reds (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) AS CIA_SEDE,
                fnc_setor_reds_7rpm (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) AS SETOR,
                fnc_tipo_validador_reds (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) AS VALIDADOR
 FROM gdo.tbl_envolvidos
 
WHERE municipio IN ('DIVINOPOLIS', 'CARMO DO CAJURU', 'CLAUDIO', 'SAO GONCALO DO PARA', 'ITAUNA', 'ITATIAIUCU') -- ('DIVINOPOLIS', 'CARMO DO CAJURU', 'CLAUDIO', 'SAO GONCALO DO PARA', 'ITAUNA', 'ITATIAIUCU')
and DATA_FATO between '2018-01-01' and '2019-12-31'

-- and nreds like '%672828-001'

and fnc_setor_reds_7rpm (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) ='other';

-- -------------------------------------------------------------------------------------------------------------

-- REDS

SELECT MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF, 
				-- fnc_companhia_reds_div (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) AS COMPANHIA_div,
               --  fnc_companhia_reds_nse (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) AS COMPANHIA_nse
              --   fnc_companhia_reds_7rpm (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) AS COMPANHIA,
                -- fnc_cia_sede_reds_7rpm (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) AS CIA_SEDE,
                fnc_fracao_reds_7rpm (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) AS FRACAO,
                fnc_setor_reds_7rpm (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) AS SETOR
				-- classificaRedsPorSetoritauna(NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) AS SETOR
                -- fnc_tipo_validador_reds (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) AS VALIDADOR
 FROM gdo.tbl_crimes
 
WHERE municipio IN ('DIVINOPOLIS', 'CARMO DO CAJURU', 'CLAUDIO', 'SAO GONCALO DO PARA', 'ITAUNA', 'ITATIAIUCU') -- ('DIVINOPOLIS', 'CARMO DO CAJURU', 'CLAUDIO', 'SAO GONCALO DO PARA', 'ITAUNA', 'ITATIAIUCU')
and DATA_FATO between '2018-01-01' and '2019-12-31'

-- and nreds like '%672828-001'

and fnc_setor_reds_7rpm (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) ='other'
-- and fnc_companhia_reds_7rpm (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) = 'other'
;
 -- -----------------------------------------------------------------------------------
 
 -- -------------------------------------------------------------------------------------------------------------

-- ARMAS

SELECT MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF, 
				-- fnc_companhia_reds_div (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) AS COMPANHIA_div,
               --  fnc_companhia_reds_nse (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) AS COMPANHIA_nse
              --   fnc_companhia_reds_7rpm (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) AS COMPANHIA,
                -- fnc_cia_sede_reds_7rpm (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) AS CIA_SEDE,
                fnc_fracao_reds_7rpm (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) AS FRACAO,
                fnc_setor_reds_7rpm (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) AS SETOR
				-- classificaRedsPorSetoritauna(NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) AS SETOR
                -- fnc_tipo_validador_reds (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) AS VALIDADOR
 FROM gdo.tbl_armas_fgo
 
WHERE municipio IN ('DIVINOPOLIS', 'CARMO DO CAJURU', 'CLAUDIO', 'SAO GONCALO DO PARA', 'ITAUNA', 'ITATIAIUCU', 'NOVA SERRANA') -- ('DIVINOPOLIS', 'CARMO DO CAJURU', 'CLAUDIO', 'SAO GONCALO DO PARA', 'ITAUNA', 'ITATIAIUCU')
and DATA_FATO between '2018-01-01' and '2019-12-31'

-- and nreds like '%672828-001'

-- and fnc_setor_reds_7rpm (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) ='other'
and fnc_companhia_reds_7rpm (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) = 'other'
;
 -- -----------------------------------------------------------------------------------
 
 

-- RAT

;
SELECT NATCODIGO, MUNICIPIO, RATNUM_ATIVIDADE, NOME_BAIRRO, LOGRADOURO, DES_ENDERECO, LOGRADOURO2, DES_ENDERECO2, COMPLEMENTO_ENDERECO, COMPLEMENTO_ALFA, LATITUDE, NOM_UNID_RESPONSAVEL,
				fnc_companhia_rat_bos_7rpm (MUNICIPIO, RATNUM_ATIVIDADE, NOME_BAIRRO, LOGRADOURO, DES_ENDERECO, LOGRADOURO2, DES_ENDERECO2, COMPLEMENTO_ENDERECO, COMPLEMENTO_ALFA, LATITUDE) as COMPANHIA,
				-- fnc_cia_sede_rat_bos (MUNICIPIO, RATNUM_ATIVIDADE, NOME_BAIRRO, LOGRADOURO, DES_ENDERECO, LOGRADOURO2, DES_ENDERECO2, COMPLEMENTO_ENDERECO, COMPLEMENTO_ALFA, LATITUDE) as CIA_SEDE,
                fnc_fracao_rat_bos_7rpm (MUNICIPIO, RATNUM_ATIVIDADE, NOME_BAIRRO, LOGRADOURO, DES_ENDERECO, LOGRADOURO2, DES_ENDERECO2, COMPLEMENTO_ENDERECO, COMPLEMENTO_ALFA, LATITUDE) as FRACAO,
                 -- fnc_cia_sede_rat_bos_NSE (RATNUM_ATIVIDADE, NOME_BAIRRO, LOGRADOURO, DES_ENDERECO, LOGRADOURO2, DES_ENDERECO2, COMPLEMENTO_ENDERECO, COMPLEMENTO_ALFA, LATITUDE) as CIA_SEDE,
				fnc_setor_rat_bos_7rpm(MUNICIPIO, RATNUM_ATIVIDADE, NOME_BAIRRO, LOGRADOURO, DES_ENDERECO, LOGRADOURO2, DES_ENDERECO2, COMPLEMENTO_ENDERECO, COMPLEMENTO_ALFA, LATITUDE) as SETOR
                -- fnc_tipo_validador_rat_bos (MUNICIPIO, RATNUM_ATIVIDADE, NOME_BAIRRO, LOGRADOURO, DES_ENDERECO, LOGRADOURO2, DES_ENDERECO2, COMPLEMENTO_ENDERECO, COMPLEMENTO_ALFA, LATITUDE) as VALIDADOR
 FROM ratbos.tbl_rat
 
 WHERE municipio IN ('DIVINOPOLIS', 'CARMO DO CAJURU', 'CLAUDIO', 'SAO GONCALO DO PARA', 'ITAUNA', 'ITATIAIUCU','NOVA SERRANA') -- ('DIVINOPOLIS', 'CARMO DO CAJURU', 'CLAUDIO', 'SAO GONCALO DO PARA', 'ITAUNA', 'ITATIAIUCU')
 AND NATCODIGO IN ('Y07001', 'Y07003', 'Y07004', 'Y07005', 'Y04012', 'Y01999', 'Y01003')
 -- AND NATCODIGO IN ('Y01003', 'Y07001')
 
 
 and DTA_INICIO between '2018-01-01' and '2020-12-31'
 -- and classificaRat_BosPorSetor(MUNICIPIO , RATNUM_ATIVIDADE, NOME_BAIRRO, LOGRADOURO, DES_ENDERECO, LOGRADOURO2, DES_ENDERECO2, COMPLEMENTO_ENDERECO, COMPLEMENTO_ALFA, LATITUDE) ='other'
 AND fnc_setor_rat_bos_7rpm (MUNICIPIO, RATNUM_ATIVIDADE, NOME_BAIRRO, LOGRADOURO, DES_ENDERECO, LOGRADOURO2, DES_ENDERECO2, COMPLEMENTO_ENDERECO, COMPLEMENTO_ALFA, LATITUDE)  ='other'
/*AND NOM_UNID_RESPONSAVEL NOT IN ('1 GP/1 PEL RV/7 CIA PM IND MAT/7 RPM','1 PEL RV/7 CIA PM IND MAT/7 RPM','1 GP/1 PEL RV/7 CIA PM RV/BPMRV/CPRV', '3 GP/1 PEL MAMB/7 CIA PM MAMB/BPM MAMB', 
'3 PEL MAMB/7 CIA PM IND MAT/7 RPM','1 PEL MAMB/7 CIA PM MAMB/BPM MAMB', 'NUCLEO DE APOIO ADMINISTRATIVO E DE FISCALIZACAO','3 GP/1 PEL MAMB/7 CIA PM MAMB/BPM MAMB', '10BBM/1CIA/3PEL (DIVINOPOLIS)', 
 '1 GP/1 PEL MAMB/7 CIA PM MAMB/BPM MAMB', 'REGIONAL OLIVEIRA', '1 GP/2 PEL MAMB/7 CIA PM IND MAT/7 RPM', '1 PEL RV/7 CIA PM RV/BPMRV/CPRV', '7 CIA PM MAMB/BPM MAMB/CPMAMB', '7 CIA PM RV/BPMRV/CPRV',
 'NUCLEO ADMINISTRATIVO E DE FISCALIZACAO', '7 CIA PM IND MAT/7 RPM', '1 CIA ROTAM/BTL ROTAM/CPE', '7 CIA PM IND PE/7 RPM', 'COORDENADORIA OESTE - FORMIGA')*/
 
 
 ;
 -- --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 -- BOS

SELECT  NATCODIGO, MUNICIPIO, RATNUM_ATIVIDADE, NOME_BAIRRO, LOGRADOURO, DES_ENDERECO, LOGRADOURO2, DES_ENDERECO2, COMPLEMENTO_ENDERECO, COMPLEMENTO_ALFA, LATITUDE, NOM_UNID_RESPONSAVEL,
		-- fnc_cia_sede_rat_bos (MUNICIPIO, RATNUM_ATIVIDADE, NOME_BAIRRO, LOGRADOURO, DES_ENDERECO, LOGRADOURO2, DES_ENDERECO2, COMPLEMENTO_ENDERECO, COMPLEMENTO_ALFA, LATITUDE) as CIA_SEDE,
        fnc_companhia_rat_bos_7rpm (MUNICIPIO, RATNUM_ATIVIDADE, NOME_BAIRRO, LOGRADOURO, DES_ENDERECO, LOGRADOURO2, DES_ENDERECO2, COMPLEMENTO_ENDERECO, COMPLEMENTO_ALFA, LATITUDE) as COMPANHIA,
        fnc_setor_rat_bos_7rpm(MUNICIPIO , RATNUM_ATIVIDADE, NOME_BAIRRO, LOGRADOURO, DES_ENDERECO, LOGRADOURO2, DES_ENDERECO2, COMPLEMENTO_ENDERECO, COMPLEMENTO_ALFA, LATITUDE) as SETOR,
        fnc_tipo_validador_rat_bos (MUNICIPIO, RATNUM_ATIVIDADE, NOME_BAIRRO, LOGRADOURO, DES_ENDERECO, LOGRADOURO2, DES_ENDERECO2, COMPLEMENTO_ENDERECO, COMPLEMENTO_ALFA, LATITUDE) as VALIDADOR
        
FROM tbl_bos
 WHERE municipio IN ('DIVINOPOLIS', 'CARMO DO CAJURU', 'CLAUDIO', 'SAO GONCALO DO PARA', 'ITAUNA', 'ITATIAIUCU', 'NOVA SERRANA') -- ('DIVINOPOLIS', 'CARMO DO CAJURU', 'CLAUDIO', 'SAO GONCALO DO PARA', 'ITAUNA', 'ITATIAIUCU')
 AND ((natCODIGO like 'a19%') or (natCODIGO like 'a20001'))
 and DTA_INICIO between '2018-01-01' and '2020-12-31'
 and fnc_setor_rat_bos_7rpm(MUNICIPIO , RATNUM_ATIVIDADE, NOME_BAIRRO, LOGRADOURO, DES_ENDERECO, LOGRADOURO2, DES_ENDERECO2, COMPLEMENTO_ENDERECO, COMPLEMENTO_ALFA, LATITUDE) ='other';
;
 