DELIMITER $$
CREATE FUNCTION fnc_ueop (MUNICIPIO VARCHAR(50)) 
RETURNS varchar (15) deterministic
BEGIN
	RETURN
		case when MUNICIPIO in ('CARMO DO CAJURU','CLAUDIO','DIVINOPOLIS','ITATIAIUCU','ITAUNA',
		'SAO GONCALO DO PARA') then '23º BPM'
		when MUNICIPIO in ('IGARATINGA','MARAVILHAS','ONCA DO PITANGUI','PAPAGAIOS',
		'PARA DE MINAS','PEQUI','SAO JOSE DA VARGINHA') then '19ª CIA PM IND' 
		when MUNICIPIO in ('ARAUJOS','CONCEICAO DO PARA','LEANDRO FERREIRA','NOVA SERRANA',
		'PERDIGAO','PITANGUI') then '60º BPM' 
		when MUNICIPIO in ('ARCOS','BAMBUI','CAMACHO','CORREGO FUNDO','FORMIGA','IGUATAMA','ITAPECERICA',
		'MEDEIROS','PAINS','PIMENTA','SAO SEBASTIAO DO OESTE','TAPIRAI') then '63º BPM' 
		when MUNICIPIO in ('ABAETE','BIQUINHAS','BOM DESPACHO','CEDRO DO ABAETE','CORREGO DANTA',
		'DORES DO INDAIA','ESTRELA DO INDAIA','JAPARAIBA','LAGOA DA PRATA','LUZ','MARTINHO CAMPOS','MOEMA',
		'MORADA NOVA DE MINAS','PAINEIRAS','PEDRA DO INDAIA','POMPEU','QUARTEL GERAL','SANTO ANTONIO DO MONTE',
		'SERRA DA SAUDADE') then '07º BPM' 
		else 'outro' end

            ;
END$$
DELIMITER ;

