DELIMITER $$
CREATE FUNCTION fnc_23bpm (MUNICIPIO VARCHAR(50))
RETURNS varchar (15)
BEGIN
	RETURN
		MUNICIPIO in ('CARMO DO CAJURU','CLAUDIO','DIVINOPOLIS','ITATIAIUCU','ITAUNA',
		'SAO GONCALO DO PARA') 

            ;
END$$
DELIMITER ;