create view vw_valid_bos as

select *, DATE_FORMAT(DTA_INICIO,'%d/%m/%Y') AS DATA_FATO_BR,
case when MUNICIPIO in ('CARMO DO CAJURU','CLAUDIO','DIVINOPOLIS','ITATIAIUCU','ITAUNA',
'SAO GONCALO DO PARA') then '23º BPM'
when MUNICIPIO in ('IGARATINGA','MARAVILHAS','ONCA DO PITANGUI','PAPAGAIOS',
'PARA DE MINAS','PEQUI','SAO JOSE DA VARGINHA') then '19ª Cia PM Ind' 
when MUNICIPIO in ('ARAUJOS','CONCEICAO DO PARA','LEANDRO FERREIRA','NOVA SERRANA',
'PERDIGAO','PITANGUI') then '60º BPM' 
when MUNICIPIO in ('ARCOS','BAMBUI','CAMACHO','CORREGO FUNDO','FORMIGA','IGUATAMA','ITAPECERICA',
'MEDEIROS','PAINS','PIMENTA','SAO SEBASTIAO DO OESTE','TAPIRAI') then '63º BPM' 
when MUNICIPIO in ('ABAETE','BIQUINHAS','BOM DESPACHO','CEDRO DO ABAETE','CORREGO DANTA',
'DORES DO INDAIA','ESTRELA DO INDAIA','JAPARAIBA','LAGOA DA PRATA','LUZ','MARTINHO CAMPOS','MOEMA',
'MORADA NOVA DE MINAS','PAINEIRAS','PEDRA DO INDAIA','POMPEU','QUARTEL GERAL','SANTO ANTONIO DO MONTE',
'SERRA DA SAUDADE') then '7º BPM' 
else 'outro' end as UEOP,
fnc_companhia_rat_bos_7rpm (MUNICIPIO, RATNUM_ATIVIDADE, NOME_BAIRRO, LOGRADOURO, DES_ENDERECO, LOGRADOURO2, DES_ENDERECO2, COMPLEMENTO_ENDERECO, COMPLEMENTO_ALFA, LATITUDE) as COMPANHIA,
fnc_cia_sede_rat_bos_7rpm (MUNICIPIO, RATNUM_ATIVIDADE, NOME_BAIRRO, LOGRADOURO, DES_ENDERECO, LOGRADOURO2, DES_ENDERECO2, COMPLEMENTO_ENDERECO, COMPLEMENTO_ALFA, LATITUDE) as CIA_SEDE,
fnc_tipo_validador_rat_bos (MUNICIPIO, RATNUM_ATIVIDADE, NOME_BAIRRO, LOGRADOURO, DES_ENDERECO, LOGRADOURO2, DES_ENDERECO2, COMPLEMENTO_ENDERECO, COMPLEMENTO_ALFA, LATITUDE) as VALIDADOR,
classificaRat_BosPorSetor(MUNICIPIO , RATNUM_ATIVIDADE, NOME_BAIRRO, LOGRADOURO, DES_ENDERECO, LOGRADOURO2, DES_ENDERECO2, COMPLEMENTO_ENDERECO, COMPLEMENTO_ALFA, LATITUDE) as SETOR,



case -- condições para crimes Reunião Comunitária
	when 	NATCODIGO like 'A19%'
	then 1
else 0
end as IC,
case -- condições para crimes Visita Tranquilizadora
	when 	NATCODIGO like 'A20001'
	then 1
else 0
end as VT,
'bos' as rel
from tbl_bos
where
((NATCODIGO like 'A19%') OR (NATCODIGO like 'A20001'))


-- NREDS not in (select NREDS from tbl_d_auditoria)

/*and*/ -- and MUNICIPIO in ('DIVINOPOLIS', 'CLAUDIO', 'CARMO DO CAJURU', 'ITAUNA','ITATIAIUCU', 'SAO GONCALO DO PARA');