create view vw_valid_materiais as 
select * -- , MONTH(DATA_FATO) AS MES,
/*CAMPO DE VALIDAÇÃO (CIA_BASE)*/
-- fnc_cia_sede_reds (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) as CIA_SEDE,
-- /*CAMPO COMPNHIA)*/
-- fnc_companhia_reds (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) as COMPANHIA,
-- /*CAMPO DE TIPO VALIDADOR (SÓ APLICADO EM DIVINÓPOLIS)*/
-- fnc_tipo_validador_reds (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) as VALIDADOR,
-- -- ************** SETORIZAÇÃO
-- classificaRedsPorSetor(MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) as SETOR
-- ************** FIM SETORIZAÇÃO
from tbl_materiais
-- where UN_REGISTRO not in (select UN_REGISTRO from tbl_un_especializada where tipo_un_registro in ('MAMB', 'RV', 'MAT', 'DER'))
where NREDS not in (select NREDS from tbl_d_auditorias)


;

