CREATE TABLE IF NOT EXISTS tbl_rpp

(
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
DATA_HORA_CADASTRO VARCHAR (100) NOT NULL,
N_LACO VARCHAR (30) NULL,
CIA_SEDE VARCHAR (50) NULL,
BAIRRO VARCHAR (50) NULL,
MEMBRO_1 VARCHAR (100) NULL,
MEMBRO_2 VARCHAR (100) NULL,
MEMBRO_3 VARCHAR (100) NULL,
LOGRADOURO VARCHAR (200) NULL,
N_LOG VARCHAR (20) NULL,
FUNCAO VARCHAR (20) NULL,
OBSERVACOES_ADD VARCHAR (200) NULL,
TELEFONE_1 VARCHAR (30) NULL,
TELEFONE_2 VARCHAR (30) NULL,
COMPLEMENTO_END VARCHAR (20) NULL,
-- COORD_GEOGRAFICAS VARCHAR (30) NULL,
LATITUDE varchar (15) NULL,
LONGITUDE varchar (15) NULL


)

ENGINE=InnoDB
DEFAULT CHARSET=utf8
;