CREATE TABLE IF NOT EXISTS tbl_quadriculas

(
ID int(11) NOT NULL AUTO_INCREMENT primary key,
FID VARCHAR (15) NULL,
OBJECTID int NULL,
NM_TXTMEMO VARCHAR (70) NULL,
MINX VARCHAR (15) NULL,
MINY VARCHAR (15) NULL,
MAXX VARCHAR (15) NULL,
MAXY VARCHAR (15) NULL,
CNTX VARCHAR (15) NULL,
CNTY VARCHAR (15) NULL,
MUNICIPIO VARCHAR (30) NULL,
TIPO VARCHAR (30) NULL,
SETOR VARCHAR (50) NULL,
LATITUDE VARCHAR (15) NULL,
LONGITUDE VARCHAR (15) NULL,
ENDE VARCHAR (50) NULL,
OPERACAO VARCHAR (30) NULL,
SUBSETOR VARCHAR (50) NULL,
SUBSETOR2 VARCHAR (50) NULL,
SUBAREA VARCHAR (11) NULL,
BAIRRO VARCHAR (50) NULL,
ENDERECO VARCHAR (200) NULL


)
default charset UTF8
ENGINE=InnoDB;


