DROP table IF EXISTS tbl_quadriculas_7rpm;

CREATE TABLE IF NOT EXISTS tbl_quadriculas_7rpm

(

FID VARCHAR (15) NULL,
OBJECTID VARCHAR (15) NULL,
MINX VARCHAR (15) NULL,
MINY VARCHAR (15) NULL,
MAXX VARCHAR (15) NULL,
MAXY VARCHAR (15) NULL,
UEOP VARCHAR (15) NULL,
MUNICIPIO VARCHAR (30) NULL,
TIPO VARCHAR (30) NULL,
SETOR VARCHAR (50) NULL,
LATITUDE VARCHAR (15) NULL,
LONGITUDE VARCHAR (15) NULL,
SUBSETOR VARCHAR (50) NULL,
SUBAREA VARCHAR (200) NULL,
ENDERECO VARCHAR (200) NULL


)
default charset UTF8
ENGINE=InnoDB;


