SELECT case when MUNICIPIO in ('CARMO DO CAJURU','CLAUDIO','DIVINOPOLIS','ITATIAIUCU','ITAUNA',
'SAO GONCALO DO PARA') then '23º BPM'
when MUNICIPIO in ('IGARATINGA','MARAVILHAS','ONCA DO PITANGUI','PAPAGAIOS',
'PARA DE MINAS','PEQUI','SAO JOSE DA VARGINHA') then '19ª Cia PM Ind' 
when MUNICIPIO in ('ARAUJOS','CONCEICAO DO PARA','LEANDRO FERREIRA','NOVA SERRANA',
'PERDIGAO','PITANGUI') then '60º BPM' 
when MUNICIPIO in ('ARCOS','BAMBUI','CAMACHO','CORREGO FUNDO','FORMIGA','IGUATAMA','ITAPECERICA',
'MEDEIROS','PAINS','PIMENTA','SAO SEBASTIAO DO OESTE','TAPIRAI') then '63º BPM' 
when MUNICIPIO in ('ABAETE','BIQUINHAS','BOM DESPACHO','CEDRO DO ABAETE','CORREGO DANTA',
'DORES DO INDAIA','ESTRELA DO INDAIA','JAPARAIBA','LAGOA DA PRATA','LUZ','MARTINHO CAMPOS','MOEMA',
'MORADA NOVA DE MINAS','PAINEIRAS','PEDRA DO INDAIA','POMPEU','QUARTEL GERAL','SANTO ANTONIO DO MONTE',
'SERRA DA SAUDADE') then '7º BPM' 
else 'outro' end as Unidade, MUNICIPIO, 

sum(case
when DTA_INICIO between '2018-01-01' and '2018-12-31' then 1 else 0 -- período integral
end) as 'Operações 2018',

sum(case
when DTA_INICIO between '2018-01-01' and '2018-03-10' then 1 else 0
end) as 'Operações 2018P',

sum(case
when DTA_INICIO between '2019-01-01' and '2019-03-10' then 1 else 0
end) as 'Operações 2019',

count(*) as TOTAL

FROM tbl_rat
 
 -- ((V2-V1)/V1 × 100)

where DTA_INICIO between '2018-01-01' and '2019-12-31'


and MUNICIPIO in ('IGARATINGA',
'MARAVILHAS',
'ONCA DO PITANGUI',
'PAPAGAIOS',
'PARA DE MINAS',
'PEQUI',
'SAO JOSE DA VARGINHA',
'CARMO DO CAJURU',
'CLAUDIO',
'DIVINOPOLIS',
'ITATIAIUCU',
'ITAUNA',
'SAO GONCALO DO PARA',
'ARAUJOS',
'CONCEICAO DO PARA',
'LEANDRO FERREIRA',
'NOVA SERRANA',
'PERDIGAO',
'PITANGUI',
'ARCOS',
'BAMBUI',
'CAMACHO',
'CORREGO FUNDO',
'FORMIGA',
'IGUATAMA',
'ITAPECERICA',
'MEDEIROS',
'PAINS',
'PIMENTA',
'SAO SEBASTIAO DO OESTE',
'TAPIRAI',
'ABAETE',
'BIQUINHAS',
'BOM DESPACHO',
'CEDRO DO ABAETE',
'CORREGO DANTA',
'DORES DO INDAIA',
'ESTRELA DO INDAIA',
'JAPARAIBA',
'LAGOA DA PRATA',
'LUZ',
'MARTINHO CAMPOS',
'MOEMA',
'MORADA NOVA DE MINAS',
'PAINEIRAS',
'PEDRA DO INDAIA',
'POMPEU',
'QUARTEL GERAL',
'SANTO ANTONIO DO MONTE',
'SERRA DA SAUDADE')
and NATCODIGO like 'y%'
AND ((HRA_INICIO between '00:00:00' and '08:00:00') OR (HRA_INICIO between '18:00:00' and '23:59:59'))
AND (
(DES_ALVO_EVENTO = 'CAIXA ELETRONICO')
OR (DES_ALVO_EVENTO = 'BANCO / CASA DE CAMBIO') --
OR (DES_LUGAR = 'BANCO / CASA DE CAMBIO')
OR (NOM_OPERACAO LIKE '%CAIXAS ELETRONICOS%')
OR (NOM_OPERACAO LIKE '%CAIXA ELETRONICO%')
OR (NOM_OPERACAO LIKE '%BANCO%')
OR (COMPLEMENTO_ENDERECO LIKE '%CAIXA ELETRONICO%')
OR (COMPLEMENTO_ENDERECO LIKE '%CAIXAS ELETRONICOS%')
)

group by municipio WITH ROLLUP