SELECT NATCODIGO, MUNICIPIO, DTA_INICIO
/*fnc_companhia_rat_bos_7rpm (MUNICIPIO, RATNUM_ATIVIDADE, NOME_BAIRRO, LOGRADOURO, DES_ENDERECO, LOGRADOURO2, DES_ENDERECO2, COMPLEMENTO_ENDERECO, COMPLEMENTO_ALFA, LATITUDE) as COMPANHIA,
fnc_fracao_rat_bos_7rpm (MUNICIPIO, RATNUM_ATIVIDADE, NOME_BAIRRO, LOGRADOURO, DES_ENDERECO, LOGRADOURO2, DES_ENDERECO2, COMPLEMENTO_ENDERECO, COMPLEMENTO_ALFA, LATITUDE) as FRACAO,
fnc_setor_rat_bos_7rpm(MUNICIPIO, RATNUM_ATIVIDADE, NOME_BAIRRO, LOGRADOURO, DES_ENDERECO, LOGRADOURO2, DES_ENDERECO2, COMPLEMENTO_ENDERECO, COMPLEMENTO_ALFA, LATITUDE) as SETOR,
*/
LATITUDE, LONGITUDE, COUNT(*) AS QTDE, fnc_ueop(MUNICIPIO) as UEOP

FROM tbl_rat

where DTA_INICIO between '2019-02-01' and '2019-12-31'

and

MUNICIPIO in ('IGARATINGA',
'MARAVILHAS',
'ONCA DO PITANGUI',
'PAPAGAIOS',
'PARA DE MINAS',
'PEQUI',
'SAO JOSE DA VARGINHA',
'CARMO DO CAJURU',
'CLAUDIO',
'DIVINOPOLIS',
'ITATIAIUCU',
'ITAUNA',
'SAO GONCALO DO PARA',
'ARAUJOS',
'CONCEICAO DO PARA',
'LEANDRO FERREIRA',
'NOVA SERRANA',
'PERDIGAO',
'PITANGUI',
'ARCOS',
'BAMBUI',
'CAMACHO',
'CORREGO FUNDO',
'FORMIGA',
'IGUATAMA',
'ITAPECERICA',
'MEDEIROS',
'PAINS',
'PIMENTA',
'SAO SEBASTIAO DO OESTE',
'TAPIRAI',
'ABAETE',
'BIQUINHAS',
'BOM DESPACHO',
'CEDRO DO ABAETE',
'CORREGO DANTA',
'DORES DO INDAIA',
'ESTRELA DO INDAIA',
'JAPARAIBA',
'LAGOA DA PRATA',
'LUZ',
'MARTINHO CAMPOS',
'MOEMA',
'MORADA NOVA DE MINAS',
'PAINEIRAS',
'PEDRA DO INDAIA',
'POMPEU',
'QUARTEL GERAL',
'SANTO ANTONIO DO MONTE',
'SERRA DA SAUDADE')
and NATCODIGO like 'y%'
group by ueop with rollup
;