SELECT *, month(DTA_INICIO) as MES, fnc_ueop(bos.municipio) as UEOP

from ratbos.tbl_bos as bos
			left join ratbos.tbl_bos_efetivos as e
			ON NUM_ATIVIDADE = RATNUM_ATIVIDADE
			-- left join ratbos.tbl_bos_efetivos as rh
			-- ON right(digitador, 7) = matricula

where DTA_INICIO between '2020-01-01' and '2020-12-31'

-- and RATNUM_ATIVIDADE = '2020-008524564-001'

and  NATCODIGO in ('X01000', 'X02000')

and bos.MUNICIPIO in (
'IGARATINGA',
'MARAVILHAS',
'ONCA DO PITANGUI',
'PAPAGAIOS',
'PARA DE MINAS',
'PEQUI',
'SAO JOSE DA VARGINHA',
'CARMO DO CAJURU',
'CLAUDIO',
'DIVINOPOLIS',
'ITATIAIUCU',
'ITAUNA',
'SAO GONCALO DO PARA',
'ARAUJOS',
'CONCEICAO DO PARA',
'LEANDRO FERREIRA',
'NOVA SERRANA',
'PERDIGAO',
'PITANGUI',
'ARCOS',
'BAMBUI',
'CAMACHO',
'CORREGO FUNDO',
'FORMIGA',
'IGUATAMA',
'ITAPECERICA',
'MEDEIROS',
'PAINS',
'PIMENTA',
'SAO SEBASTIAO DO OESTE',
'TAPIRAI',
'ABAETE',
'BIQUINHAS',
'BOM DESPACHO',
'CEDRO DO ABAETE',
'CORREGO DANTA',
'DORES DO INDAIA',
'ESTRELA DO INDAIA',
'JAPARAIBA',
'LAGOA DA PRATA',
'LUZ',
'MARTINHO CAMPOS',
'MOEMA',
'MORADA NOVA DE MINAS',
'PAINEIRAS',
'PEDRA DO INDAIA',
'POMPEU',
'QUARTEL GERAL',
'SANTO ANTONIO DO MONTE',
'SERRA DA SAUDADE')


-- and NUM_MATRICULA = '1242411'
-- group by NUM_MATRICULA
;