SELECT
UEOP AS UNIDADE, 
-- UN_REGISTRO,
SUM(EFETIVO) AS EFETIVO,
-- SUM(VIATURAS) AS VIATURAS, # NÃO FUNCIONA
SUM(PESSOAS_PRESAS) AS PESSOAS_PRESAS,
SUM(PESSOAS_APREENDIDAS) AS PESSOAS_APREENDIDAS,
SUM(MANDADOS_BUSCA_APREENSAO) AS MANDADOS_BUSCA_APREENSAO,
SUM(PESSOAS_PRESAS_MANDADO) AS PESSOAS_PRESAS_MANDADO,
SUM(MANDADOS_PRISAO_CUMPRIDOS) AS MANDADOS_PRISAO_CUMPRIDOS,
SUM(PES_PRESAS_TRAFICO_DROGAS) AS PES_PRESAS_TRAFICO_DROGAS,
SUM(PES_PRESAS_HOMICIDIO) AS PES_PRESAS_HOMICIDIO,
SUM(PES_PRESAS_ROUBO) AS PES_PRESAS_ROUBO,
SUM(PES_PRESAS_FURTO) AS PES_PRESAS_FURTO,
SUM(REVOLVER) + SUM(ESPINGARDA) + SUM(PISTOLA) + SUM(OUTRAS_ARMAS) AS ARMA_FGO,
-- SUM(ESPINGARDA) AS ESPINGARDA,
-- SUM(PISTOLA) AS PISTOLA,
SUM(ARMAS_FGO) AS ARMAS_FOGO,
SUM(MUNICOES_UN) AS MUNICOES,
SUM(ARMAS_DE_PRESSAO) AS ARMA_DE_PRESSAO,
SUM(SIMULACRO) AS SIMULACRO,
SUM(ARMAS_BRANCA) AS ARMAS_BRANCA,
SUM(CRACK_PEDRAS_UN) AS CRACK_PEDRAS_UN,
SUM(CRACK_GR) AS CRACK_GR,
SUM(MACONHA_TABLETE_GR) AS MACONHA_TABLETE_GR,
SUM(MACONHA_BUCHA_UN) AS MACONHA_BUCHA_UN,
SUM(CIGARRO_MACONHA_UN) AS CIGARRO_MACONHA_UN,
SUM(COCAINA_PAPELOTE_UN) AS COCAINA_PAPELOTE_UN,
SUM((COCAINA_PASTA_GR + COCAINA_OUTROS_GR + COCAINA_EM_PO_GR)) AS COCAINA_GR,
SUM(HAXIXE_EM_BOLA_UN) AS HAXIXE_EM_BOLA_UN,
SUM(ECSTASE_UN) AS ECSTASE_UN,
SUM(LSD_UN) AS LSD_UN,
SUM(DROGAS_OUTRAS_UN) AS DROGAS_OUTRAS_UN,
SUM(TELEFONE_CELULAR_UN) AS TELEFONE_CELULAR_UN,
SUM(MICRO_COMPUTADOR_UN) AS MICRO_COMPUTADOR_UN,
SUM(VEICULOS_APREENDIDOS) AS VEICULOS_APREENDIDOS,
SUM(VEICULOS_RECUPERADOS) AS VEICULOS_RECUPERADOS,
SUM(AIT) AS AIT,
COUNT(*) AS REDS_REGISTRADOS
-- SUM(if(COD_DIAO = 'C01157' AND T_C = 'CONSUMADO', 1, 0)) as 'ROUBO'

-- sum(if(month(data_fato) = 1, 1, 0)) as 'JAN',
FROM pdca.vw_pdca

-- WHERE NREDS IN ('2019-058581956-001')


WHERE DATA_FATO BETWEEN '2019-01-01' AND '2019-01-31'
-- MUNICIPIO IN ('DIVINOPOLIS', 'CARMO DO CAJURU', 'CLAUDIO', 'SAO GONCALO DO PARA', 'ITAUNA', 'ITATIAIUCU')
-- AND UN_REGISTRO NOT LIKE '7 CIA PM IND PE/7 RPM'
GROUP BY UEOP with rollup
 ;