SELECT FNC_UEOP(MUNICIPIO) UEOP,

 

 sum(QTDE_ENVOL) ,
 
 
  case
		when PRISAO_APREES in ('FLAGRANTE DE CRIME / CONTRAVENCAO', 'RECAPTURA', 'OUTRAS - PRISAO / APREENSAO','MANDADO JUDICIAL', 'FLAGRANTE DE ATO INFRACIONAL') 
	
		then count(distinct(concat(NREDS, NOME_ENVOL)))
		
		else (0)
	end	as PESSOAS_PRESAS, -- ok
    
    
    
  case
		when PRISAO_APREES in ('FLAGRANTE DE CRIME / CONTRAVENCAO', 'RECAPTURA', 'OUTRAS - PRISAO / APREENSAO','MANDADO JUDICIAL', 'FLAGRANTE DE ATO INFRACIONAL') 
	 
		then sum(distinct(QTDE_ENVOL))
		
		else (0)
	end	as PESSOAS_PRESAS -- ok
 
 
 FROM pdca.tbl_envolvidos
 


WHERE -- DATA_FATO BETWEEN '2019-09-21' AND '2019-09-30'
 PRISAO_APREES in ('FLAGRANTE DE CRIME / CONTRAVENCAO', 'RECAPTURA', 'OUTRAS - PRISAO / APREENSAO','MANDADO JUDICIAL', 'FLAGRANTE DE ATO INFRACIONAL') 
	

AND COD_DIAO = 'C01157'

group by ueop with rollup


;