CREATE TABLE tbl_rat_efetivos (
  ID int NOT NULL AUTO_INCREMENT,
  NUM_ATIVIDADE varchar(19) NOT NULL,
  NUM_MATRICULA varchar(15) DEFAULT NULL,
  NOME varchar(50) DEFAULT NULL,
  NOM_CARGO varchar(20) DEFAULT NULL,
  COD_UNIDADE_SERVICO varchar(6) DEFAULT NULL,
  NOM_UNIDADE varchar(50) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY NUM_ATIVIDADE (NUM_ATIVIDADE),
  FOREIGN KEY (NUM_ATIVIDADE) REFERENCES tbl_rat (RATNUM_ATIVIDADE)
) 
ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4;







/*CREATE TABLE tbl_rat_efetivo (
  ID int(11) NOT NULL AUTO_INCREMENT,
  NUM_ATIVIDADE varchar(19) NOT NULL,
  NUM_MATRICULA varchar(15) DEFAULT NULL,
  NOME varchar(50) DEFAULT NULL,
  NOM_CARGO varchar(20) DEFAULT NULL,
  COD_UNIDADE_SERVICO varchar(5) DEFAULT NULL,
  NOM_UNIDADE varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY NUM_ATIVIDADE (NUM_ATIVIDADE),
  CONSTRAINT `tbl_rat_efetivo_ibfk_1` FOREIGN KEY (NUM_ATIVIDADE) REFERENCES tbl_rat (RATNUM_ATIVIDADE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




/*CREATE TABLE IF NOT EXISTS tbl_rat_efetivo

(
ID INT AUTO_INCREMENT NOT NULL primary key, -- verificar   a utilidade desse campo id POIS  NAO  ESTA DANDO CERTO
NUM_ATIVIDADE varchar(18) not null,
NUM_MATRICULA varchar(15) null,
NOME varchar(50) null,
NOM_CARGO varchar(20) null,
COD_UNIDADE_SERVICO varchar(5),
NOM_UNIDADE varchar(50) null
-- FOREIGN KEY (NUM_ATIVIDADE) -- TABELA ONDE TEM MUITOS REGISTROS
-- references TBL_RAT(idcurso);
)
DEFAULT CHARSET = utf8
ENGINE=InnoDB;*/