CREATE TABLE IF NOT EXISTS tbl_ddu

(

PRAZO_RESPOSTA 	DATE NULL,
RESTANTE 		VARCHAR (30) NULL,
DATA_DEN 		DATE NULL,
DDU				varCHAR (12) NOT NULL PRIMARY KEY,
ASSUNTO			VARCHAR (100) NULL,
ENDERECO 		VARCHAR (100) NULL,
BAIRRO			VARCHAR (50) NULL,
MUNICIPIO 		VARCHAR (50) NULL,
CEP				VARCHAR (50) NULL,
DENUNCIADO		VARCHAR (200) NULL,
CIA_BASE		VARCHAR (10) NULL,
DOCUMENTO 		VARCHAR (30) NULL,
SUCESSO			VARCHAR (5) NULL,
NATUREZA 		VARCHAR (7) NULL,
DATA_RESPOSTA 	DATE NULL,
CONCLUSAO 		VARCHAR (1000) NULL

)

ENGINE=InnoDB;

