CREATE TABLE IF NOT EXISTS tbl_auditorias

(



NREDS VARCHAR (18) PRIMARY KEY,
DATA_PA DATE,
PROTOCOLO 	varCHAR (20),
MOTIVO VARCHAR (600),
UEOP  VARCHAR (20),
COMPANHIA VARCHAR (11),
MUNICIPIO VARCHAR (50),
COD_DIAO VARCHAR (11),
NATUREZA VARCHAR (50),
ACAO VARCHAR (20)
)

ENGINE=InnoDB;
