CREATE TABLE IF NOT EXISTS tbl_transacional

(

NREDS VARCHAR (18) NOT NULL PRIMARY KEY,
COD_DIAO CHAR (6),
DESC_DIAO VARCHAR (30),
T_C VARCHAR (9) NULL,
ORG_UN_REG VARCHAR (30) NULL,
UN_RESP VARCHAR (100) NULL,
UN_RESP_NOME VARCHAR (100) NULL,
DATA_FATO DATE NULL,
HORA_FATO TIME NULL,
MUNICIPIO VARCHAR (50) NULL,
LATITUDE varchar (15) NULL,
LONGITUDE varchar (15) NULL,
COD_MUNI VARCHAR (20),
HISTORICO TEXT,
LOG_TIPO VARCHAR (20) NULL,
LOGRADOURO VARCHAR (100) NULL,
LOGRADOURO_NAO_CAD VARCHAR (100) NULL,
COMPLEMENTO_END VARCHAR (20) NULL,
N_LOG VARCHAR (20) NULL,
N_LOG_COMPL VARCHAR (20) NULL,
LOG_TIPO_CRUZ VARCHAR (20) NULL,
LOGRADOURO_CRUZ VARCHAR (100) NULL,
LOGRADOURO_CRUZ_NAO_CAD VARCHAR (100) NULL,
BAIRRO VARCHAR (50) NULL,
BAIRRO_NAO_CAD VARCHAR (50) NULL,
PONTO_REF VARCHAR (5) NULL,
UN_AREA_MIL VARCHAR (100) NULL,
UN_AREA_MIL_NOME VARCHAR (100) NULL,
COD_AREA_CIVIL VARCHAR (50) NULL,
NOME_AREA_CIVIL VARCHAR (50) NULL,
COD_COMPL VARCHAR (30) NULL,
DESC_COMPL VARCHAR (50) NULL,
COD_TIPO_LOCAL VARCHAR (6),
DESC_TIPO_LOCAL VARCHAR (100),
COD_INSTRUMENTO_UTIL  VARCHAR (20),
DESC_INSTRUMENTO_UTIL VARCHAR (100),
DATA_REG DATE NULL,
HORA_REG TIME NULL,
UEOP varchar (15) NULL,
COMPANHIA VARCHAR (30) NULL,
-- CIA_SEDE VARCHAR (30) NULL,
FRACAO VARCHAR (50) NULL,
SETOR varchar (50) NULL,
VALIDADOR varchar (30) NULL



)
DEFAULT CHARSET = utf8
ENGINE=InnoDB;