CREATE TABLE IF NOT EXISTS tbl_gdo_ref_2017

(

NREDS varCHAR (18) NOT NULL PRIMARY KEY,
ASSOCIADO varchar (3),
ORG_UN_REG VARCHAR (30) NULL,
COD_DIAO CHAR (6),
T_C VARCHAR (9) NULL,
ALVO VARCHAR (30) NULL,
-- DESC_MEIO_UTILIZADO VARCHAR (100) NULL,
DATA_FATO DATE NULL,
DEZENA VARCHAR (20) NULL,
HORA TIME NULL,
LOG_TIPO VARCHAR (20) NULL,
LOGRADOURO VARCHAR (100) NULL,
N_LOG VARCHAR (15) NULL,
BAIRRO VARCHAR (50) NULL,
BAIRRO_FINAL VARCHAR (100) NULL,
UEOP VARCHAR (15) NULL,
CIA_BASE VARCHAR (100) NULL,
MUNICIPIO VARCHAR (50) NULL,
LATITUDE VARCHAR (15) NULL,
LONGITUDE VARCHAR (15) NULL,
QTDE varchar (30) NULL

)

ENGINE=InnoDB;