DROP TABLE IF EXISTS tbl_homicidios_2019_ref;


CREATE TABLE IF NOT EXISTS tbl_homicidios_2019_ref

(
ID_ENV int primary KEY auto_increment,
NREDS varchar (18) NOT NULL,
ORG_UN_REG VARCHAR (30),
UN_AREA_MIL VARCHAR (50) NULL,
UN_REGISTRO VARCHAR (100) NULL,
COD_DIAO CHAR (6),
T_C VARCHAR (9) NULL,
COD_DELITO CHAR (7),
T_C_DELITO VARCHAR (22) NULL,
GRAU_LESAO VARCHAR (25) NULL,
GRUPO_TIPO_ENVOL VARCHAR (50) NULL,
TIPO_ENVOLVIMENTO VARCHAR (50) NULL,
PRISAO_APREES VARCHAR (50) NULL,
DATA_FATO DATE NULL,
HORA TIME NULL,
DATA_ULT_ATT DATE NULL,
LOG_TIPO VARCHAR (20) NULL,
LOGRADOURO VARCHAR (100) NULL,
LOGRADOURO_NAO_CAD VARCHAR (100) NULL,
LOGRADOURO_CRUZ VARCHAR (100) NULL,
LOGRADOURO_CRUZ_NAO_CAD VARCHAR (100) NULL,
N_LOG VARCHAR (20) NULL,
BAIRRO VARCHAR (50) NULL,
BAIRRO_NAO_CAD VARCHAR (50) NULL,
COMPLEMENTO_END VARCHAR (50) NULL,
PONTO_REF VARCHAR (50) NULL,
MUNICIPIO VARCHAR (50) NULL,
LATITUDE VARCHAR (15) NULL,
LONGITUDE VARCHAR (15) NULL,
NOME_ENVOL VARCHAR (100) NULL,
DATA_NASC DATE NULL,
SEXO VARCHAR (22) NULL,
CUTIS VARCHAR (50) NULL,
IDADE VARCHAR (50) NULL,
ESTADO_CIVIL VARCHAR (50) NULL,
OCUPACAO VARCHAR (50) NULL,
ESCOLARIDADE VARCHAR (50) NULL,
LOGRADOURO_ENVOL VARCHAR (100) NULL,
BAIRRO_ENVOL VARCHAR (50) NULL,
TIPO_LOG_ENVOL VARCHAR (18) NULL,
MUNICIPIO_ENVOL VARCHAR (50) NULL,
QTDE_ENVOL varchar (30) NULL,
UEOP varchar (15) NULL,
COMPANHIA VARCHAR (30) NULL,
-- CIA_SEDE VARCHAR (30) NULL,
FRACAO VARCHAR (50) NULL,
SETOR varchar (50) NULL,
VALIDADOR varchar (30) NULL


)
DEFAULT CHARSET = utf8mb4
ENGINE=InnoDB;