drop view if exists vw_valid_materiais;

create view vw_valid_materiais as 
select * -- , MONTH(DATA_FATO) AS MES,
/*CAMPO DE VALIDAÇÃO (CIA_BASE)*/
-- fnc_cia_sede_reds (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) as CIA_SEDE,
-- /*CAMPO COMPNHIA)*/
-- fnc_companhia_reds (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) as COMPANHIA,
-- /*CAMPO DE TIPO VALIDADOR (SÓ APLICADO EM DIVINÓPOLIS)*/
-- fnc_tipo_validador_reds (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) as VALIDADOR,
-- -- ************** SETORIZAÇÃO
-- classificaRedsPorSetor(MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) as SETOR
-- ************** FIM SETORIZAÇÃO
from tbl_materiais

where  UN_REGISTRO not in (select UN_REGISTRO from tbl_un_especializada where tipo_un_registro in ('DER', 'MAT', 'MAMB', 'RV', 'CPE')) 

AND COD_DIAO = 'C01157'


OR NREDS in (select NREDS from tbl_controle_auditorias where INDICADOR IN ('ACERTO DE TRI/INCLUSAO ARMA DE FOGO') AND AUDITADO = 'SIM')

;

