create view vw_valid_envolvidos as
select *, -- , MONTH(DATA_FATO) AS MES,

/*CAMPO DE VALIDAÇÃO (CIA_BASE)*/
-- fnc_cia_sede_reds (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) as CIA_SEDE,
/*CAMPO COMPNHIA)*/
-- fnc_companhia_reds (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) as COMPANHIA,
/*CAMPO DE TIPO VALIDADOR (SÓ APLICADO EM DIVINÓPOLIS)*/
-- fnc_tipo_validador_reds (MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) as VALIDADOR,
-- ************** SETORIZAÇÃO
-- classificaRedsPorSetor(MUNICIPIO, NREDS, BAIRRO, BAIRRO_NAO_CAD, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, COMPLEMENTO_END, PONTO_REF) as SETOR,
-- ************** FIM SETORIZAÇÃO

case -- condições para HOMICIDIOS
		when  (( -- INÍCIO CONDIÇÃO PRINCIPAL		
				(COD_DIAO in ('B01121') and T_C = 'CONSUMADO')	  
				or  COD_DELITO in ('B01121') and T_C_DELITO = 'CONSUMADO')
			) -- FIM CONDIÇÃO PARA  (NATUREZAS)

AND GRAU_LESAO = 'FATAL'
AND GRUPO_TIPO_ENVOL = 'VITIMA'
       
	        
    then 1
else 0
end as HC_VITIMA,

case -- calcula quantidade de presos
			
		WHEN	(ORG_UN_REG = 'POLICIA MILITAR') -- COND2
        AND
        (
				(COD_DIAO IN ('B01121', 'C01157', 'D01213','D01217') AND T_C in ('CONSUMADO', 'TENTADO'))
         OR
				(COD_DIAO in ('B01148', 'C01158', 'C01159') AND T_C = 'CONSUMADO')
		 OR
				(COD_DIAO = 'C01158' and T_C = 'TENTADO')
		 
         
         -- ---------------------------------------------------------------------------------- EM TESTE
         OR
         		(COD_DELITO IN ('B01121', 'C01157', 'D01213','D01217') AND T_C_DELITO in ('CONSUMADO', 'TENTADO'))
         OR
				(COD_DELITO  in ('B01148', 'C01158', 'C01159') AND T_C_DELITO = 'CONSUMADO')
		 OR
				(COD_DELITO  = 'C01158' and T_C_DELITO = 'TENTADO')

        )

AND
        (PRISAO_APREES IN ('FLAGRANTE DE ATO INFRACIONAL', 'FLAGRANTE DE CRIME / CONTRAVENCAO'))
        then 1 else 0 -- crimes do mês anterior
end as NPAA,

/*case when MUNICIPIO in ('CARMO DO CAJURU','CLAUDIO','DIVINOPOLIS','ITATIAIUCU','ITAUNA',
'SAO GONCALO DO PARA') then '23º BPM'
when MUNICIPIO in ('IGARATINGA','MARAVILHAS','ONCA DO PITANGUI','PAPAGAIOS',
'PARA DE MINAS','PEQUI','SAO JOSE DA VARGINHA') then '19ª Cia PM Ind' 
when MUNICIPIO in ('ARAUJOS','CONCEICAO DO PARA','LEANDRO FERREIRA','NOVA SERRANA',
'PERDIGAO','PITANGUI') then '60º BPM' 
when MUNICIPIO in ('ARCOS','BAMBUI','CAMACHO','CORREGO FUNDO','FORMIGA','IGUATAMA','ITAPECERICA',
'MEDEIROS','PAINS','PIMENTA','SAO SEBASTIAO DO OESTE','TAPIRAI') then '63º BPM' 
when MUNICIPIO in ('ABAETE','BIQUINHAS','BOM DESPACHO','CEDRO DO ABAETE','CORREGO DANTA',
'DORES DO INDAIA','ESTRELA DO INDAIA','JAPARAIBA','LAGOA DA PRATA','LUZ','MARTINHO CAMPOS','MOEMA',
'MORADA NOVA DE MINAS','PAINEIRAS','PEDRA DO INDAIA','POMPEU','QUARTEL GERAL','SANTO ANTONIO DO MONTE',
'SERRA DA SAUDADE') then '7º BPM' 
else 'outro' end as UEOP,*/
case
	when NREDS not in (select NREDS from tbl_auditorias) then 1
else 0
end as Auditoria
from tbl_envolvidos
-- where UN_REGISTRO not in (SELECT UN_REGISTRO FROM tbl_un_especializada);

where NREDS not in (select NREDS from tbl_auditorias)




